
from email.mime import text 
import pyautogui # Importação da biblioteca Pyautogui para controle do mouse e teclado 
import time # Importação da biblioteca time para intervalos de tempo 
import re # Importação da biblioteca re para modificação de strings
import pickle # Importação da biblioteca pickle para salvar arquivos
from pyscreeze import screenshot # Importação da biblioteca pyscreeze para captura de tela
from pytesseract import pytesseract # Importação da biblioteca pytesseract para conversão de imagens em strings
caminho_tesseract = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe" # Caminho para o executável do pytesseract
pytesseract.tesseract_cmd = caminho_tesseract # Define o caminho para o pytesseract
tempo_de_execucao = 40000 # Tempo de execução máximo da operação 


grupos = {
    'colorometria': {
        'codigo': '0006',
        'subgrupos': {
            'default':{'código': '0001', 'itens': []}

        }
    },
    'parabrisas': {
        'codigo': '0005',
        'subgrupos': {
            'sem_sensor': {'codigo': '0002', 'itens': ["PARABRISA", "PARABRISA S/SENSOR", "PARABRISA S/ SENSOR", "PARABRISA SISENSOR", "PARABRISA SEM SENSOR"]},
            'com_sensor': {'codigo': '0003', 'itens': ["PARABRISA C/SENSOR", "PARABRISA C/ SENSOR", "PARABRISA COM SENSOR", "PARABRISA SENSOR", "PARABRISA CISENSOR"]}
        }
    },
    'vigias': {
        'codigo': '0003',
        'subgrupos': {
            'default':{'codigo': '0001', 'itens': ['VIDRO VIGIA', 'VIGIA']}}
    },
    'laterais': {
        'codigo': '0008',
        'subgrupos': {
            'ventarolas': {'codigo': '0004', 'itens': ['VENTAROLA', 'VIDRO LATERAL MOVEL', 'VIDRO VENTAROLA', 'VIDRO VENTAROLA OCULO']},
            'vidros_ocolus': {'codigo': '0005', 'itens': ['OCULO', 'OCULOS', 'VIDRO LATERAL DIANT', 'VIDRO LATERAL OCULO', 'VIDRO LATERAL TRAS OCULO', 'VIDRO FIXO DIANTEIRO']},
            'vidros_janela': {'codigo': '0006', 'itens': ['VIDRO JANELA', 'VIDRO LATERAL TRAS', 'VIDRO LATERAL', 'VIDRO LATERAL FIXO', 'VIDRO PORTA FIXO']},  
            'vidros_porta': {'codigo': '0007', 'itens': ['VIDRO PORTA']},
        }
    },
    'baterias_startstop': {
        'codigo': '0009',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BATERIA START STOP', 'BATERIA START STOP', 'BATERIA START-STOP']},

        }
    },
    'baterias_nobreak': {
        'codigo': '0010',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BATERIA NOBREAK', 'BATERIA NOOBREAK']},

        }
    },
    'escapamentos_completos': {
        'codigo': '0011',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'coxins': {'codigo': '0078', 'itens': ['COXIM SILENCIOSO', 'COXIM ESCAPAMENTO', 'KIT COXIM ESCAPAM']},

        }
    },
    'escapamentos_silenciosos': {
        'codigo': '0012',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ESCAPAMENTO TRAS', 'ESCAPAMENTO TRASEIRO', 'ESCAPAMENTO SILENC', 'ESCAPAMENTO SILENCIOSO TRAS', 'ESCAPAMENTO SIL TRAS', 'ESCAPAMENTO SILENCIOSO TRAS', 'ESCAPAMENTO ABAF', 'ESCAPAMENTO ABAFADOR', 'ESCAPAMENTO CONJUNT', 'ESCAPAMENTO TURBINHO', 'ESCAPAMENTO TURBINHO']},

        }
    },
    'escapamentos_catalisadores': {
        'codigo': '0013',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CATALISADOR ESCAP', 'ESCAPAMENTO CATALISA']},

        }
    },
    'escapamentos_coletores': {
        'codigo': '0014',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ESCAPAMENTO COLETOR', 'ESCAPAMENTO COLETOR TUBULAR']},

        }
    },
    'escapamentos_coletores_catalisador': {
        'codigo': '0015',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CATALISADOR C/TB', 'CATALISADOR C/TUBO', 'COLETOR COM CATALIS']},

        }
    },
    'escapamentos_intermediarios': {
        'codigo': '0016',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BENGALA ESCAPAMENTO', 'CURVA ESCAPAMENTO', 'ESCAPAMENTO INTER', 'ESCAPAMENTO INTERM', 'ESCAPAMENTO INTEMEDIARIO', 'ESCAPAMENTO ABAF INTER', 'ESCAPAMENTO ABAFADOR INTERM', 'ESCAPAMENTO SIL INTER', 'ESCAPAMENTO TUBO INTER', 'TUBO INTER' ]},

        }
    },
    'escapamentos_ponteiras': {
        'codigo': '0017',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['PONTEIRA', 'PONTEIRA ESCAP']},

        }
    },
    'escapamentos_tubos': {
        'codigo': '0018',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['TUBO ESCAP', 'ESCAPAMENTO TUBO', 'LUVA ESCAP', 'TUBO MOTOR']},

        }
    },
    'escapamentos_flexiveis': {
        'codigo': '0019',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ESCAPAMENTO C/FLEX', 'ESCAPAMENTO COM FLEXIVEL', 'ESCAPAMENTO FLEXIVEL', 'FLEXIVEL ESCAP']},

        }
    },
    'ar_condicionado': {
        'codigo': '0037',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CONJUNTO EMBREAGEM COMPRESSOR', 'MAGNETICO COMPRESSOR']},
        }
    },
    'arrefecimento': {
        'codigo': '0020',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BRUCUTU', 'BUCHA BOMBA ESGUICHO', 'KIT CAVALETE DISTR AGUA', 'PRESILHA FIX SUPORTE RADIADOR', 'SUPORTE COXIM RADIADOR']},
            'buchas_arrefecimento': {'codigo': '0113', 'itens': ['BUCHA RADIADOR', 'BUCHA BOMBA ESGUICHO', 'BUCHA RESERVATORIO GAS PARTIDA']},
            'radiadores': {'codigo': '0008', 'itens': ['RADIADOR', 'RADIADOR AGUA']},
            'bombas_agua': {'codigo': '0009', 'itens': ['BOMBA AGUA', 'BOMBA D.HIDR', 'BOMBA DAGUA']},
        }
    },
    'cabos': {
        'codigo': '0021',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CABO ACIONADOR PORTINHOLA', 'CABO AR FORCADO', 'CABO PORTA CORRER', 'CABO PORTA MALA', 'CABO PORTINHOLA', 'CABO TEMPERATURA', 'PARAFUSO QUEBRA GALHO CABO ACELERADOR']},
            'cabos_acelerador': {'codigo': '0011', 'itens': ['CABO ACEL', 'CABO ACELERADO', 'CABO DE ACELERADOR', 'CABO PARADA MOTOR']},
            'cabos_embreagem': {'codigo': '0012', 'itens': ['CABO EMB', 'CABO EMBR', 'CABO EMBREAGE', 'CABO FLEX EMBR', 'CABO TRANSMISSAO', 'FLEXIVEL EMBREAGEM']},
            'cabos_freio': {'codigo': '0013', 'itens': ['CABO DE FREIO', 'CABO FREIO', 'CABO LIBERACAO FREIO']},
            'cabos_capo': {'codigo': '0014', 'itens': ['CABO CAPO', 'CABO PUXADOR CAPO']},
            'cabos_velocimetro': {'codigo': '0015', 'itens': ['CABO DE VELOCIMETRO', 'CABO TACOGRAFO', 'CABO TACOMETRO', 'CABO VELOCIMETRO', 'CABO VELOC']},
            'cabos_tampa_traseira': {'codigo': '0016', 'itens': ['CABO LIMITADOR DA TAMPA TRAS', 'CABO PUXADOR TAMPA', 'CABO TAMPA TRAS']},
            'cabos_afogador': {'codigo': '0017', 'itens': ['CABO AFOGADOR', 'CABO ESTRANGULADOR']},
            'cabos_cambio': {'codigo': '0018', 'itens': ['CABO CAMBIO', 'CABO COMANDO', 'CABO COMANDO MARCHA', 'CABO ENGATE COMANDO', 'CABO ENGATE', 'CABO ENGATE MARCHA', 'CABO MARCHA', 'CABO REDUZIDA', 'CABO SELECAO CAMBIO', 'CABO SELECAO MARCHA', 'CABO SELECAO COMANDO']},
            'cabos_fechadura': {'codigo': '0019', 'itens': []},
            'cabos_trava_banco': {'codigo': '0020', 'itens': ['CABO ENCOSTO BANCO', 'CABO REGULAGEM BANCO', 'CABO TRAVA BANCO', 'CABO BANCO']},
            'terminais_cabo': {'codigo': '0151', 'itens': ['TERMINAL CABO COMANDO', 'TERMINAL CABO ENGATE', 'TERMINAL CABO MARCHA', 'TERMINAL CABO SELECAO']},
        }
    },
    'carburacao': {
        'codigo': '0022',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['AVANCO DISTRIBUIDOR', ' BOIA CARBURADOR', 'AFOGADOR', 'AVANCO DO DISTRIBUIDOR',   'CONJUNTO VALVULA BOIA CARBURADOR', 'EIXO CARBURADOR', 'KIT POSICIONADOR AFOGADOR', 'PORTA GICLE MARCHA CARBURADOR', "SAPATILHA CAME DEFOGADOR CARBURADOR"]},
            'carburadores': {'codigo': '0021', 'itens': ['CARBURADOR', 'KIT CARBURADOR']},
            'componentes_carburadores': {'codigo': '0022', 'itens': ["AGULHA CARBURADOR", 'BASE CARB', 'BASE CARBURADOR', 'BASE VEDACAO CARB', 'BENGALA CARB', 'BENGALA INJETOR CARBURAD', 'BORBOLETA CARBURADOR', 'ESGUICHO CARB', 'GICLE CARBURADOR', 'HASTE CARBURADOR', 'ESGUICHO CARBURADOR', 'ESPACADOR BASE CARB',  'FILTRO DIFUSOR SECUNDARIO', 'PISTAO ANEL MOTOR', 'PISTAO REPARO PINCA', 'PISTAO CARBURADOR']},
            'diafragmas_carburadores': {'codigo': '0122', 'itens': ['DIAFRAGMA CARBURADO', 'DIAFRAGMA ACELERA']},
        }
    },
    'carcacas_tubos': {
        'codigo': '0035',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['PORCA FLANGE COMB', 'PROTETOR CALOR CAIXA AR', 'VENTURI CARBURADOR']},
            'antichama': {'codigo': '0105', 'itens': ['ANTICHAMA', 'ANTI CHAMA', 'DEFLETOR ANTICHAMA']},
            'cavaletes': {'codigo': '0106', 'itens': ['CAVALETE', 'FLANGE CAVALETE AGUA']},
            'tubos': {'codigo': '0107', 'itens': ['TUBO ABASTECIMENTO', 'TUBO RESPIRO', 'TUBO AGUA', 'TUBO AR PAINEL', 'TUBO CILINDRO', 'TUBO CIRCULACAO AGUA', 'TUBO COLETOR', 'TUBO CIRCULACAO', 'TUBO COLETOR', 'TUBO COMBUSTIVEL', 'TUBO CONEXAO', 'TUBO DISTRIBUIDOR', 'TUBO FLANGE', 'TUBO FLUXO AGUA', 'TUBO GARGALO', 'TUBO LIGACAO', 'TUBO MANGUEIRA', 'TUBO MISTURADOR CARBURADOR', 'TUBO MOTOR', 'TUBO RADIADOR', 'TUBO REFRIGERACAO', 'TUBO RETORNO', 'TUBO SUPERIOR', 'TUBO VENTILACAO', 'TUBO CONEXAO BOMBA', 'TUBO CANO EMBREAGEM', 'TUBO CORRUGADO BOMBA', 'TUBO MANGUEIRA DIRECAO', 'TUBO MANGUEIRA TANQUE']},
            'conectores': {'codigo': '0108', 'itens': ['CONECTOR LIGACAO MANGUEIRA', 'CONECTOR MANGUEIRA', 'CONECTOR 3/8', 'CONECTOR AGUA', 'CONECTOR CAMB', 'CONECTOR DUPLO UNIVE', 'CONECTOR GASOLINA', 'CONECTOR QUICK', 'CONECTOR SELADO', 'CONECTOR UNIVERSAL', 'CONEXAO RESERVATORIO', 'CONEXAO AGUA', 'CONEXAO CARC VALV', 'CONEXAO COM REGISTRO', 'CONEXAO DUPLA MANG', 'CONEXAO ESGUICHO', 'CONEXAO INF', 'CONEXAO MANG', 'CONEXAO RAPIDA', 'CONEXAO RADIADOR', 'CONEXAO Y DUPLO', 'EMENDA CONEXAO']},
            'cotovelos': {'codigo': '0109', 'itens': ['CONEXAO (COTOVELO)', 'COTOVELO', 'COTOVELO CAVALETE']},
            'capas_correias': {'codigo': '0110', 'itens': ['CAPA CORREIA', 'JOGO PROTETOR CORREIA', 'KIT CAPA PROTETOR CORREIA', 'KIT CAPA CORREIA', 'KIT PROTETOR CORREIA', 'PROTETOR CORREIA']},
            'carcacas': {'codigo': '0111', 'itens': ['CARCACA', 'CAIXA FILTRO AR', 'CAIXA FILTRO AR CARB', 'CAMARA VALVULA TERMOS']},
            'flanges': {'codigo': '0131', 'itens': ['FLANGE  MOTOR', 'FLANGE MANG CABECOTE', 'FLANGE AGUA', 'FLANGE BOMBA DAGUA', 'FLANGE CONEXAO', 'FLANGE ROLAMENTO CAIXA CAMBIO', 'FLANGE SEMI EIXO', 'FLANGE TERMOSTATO', 'FLAGE TUBO MANGUEIRA', 'FLANGE VALV TERMOST']},
            'kits_carcacas': {'codigo': '0112', 'itens': []},
        }
    },
    'combustivel': {
        'codigo': '0034',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ADAPTADOR TAMPA TANQUE", 'BORRACHA FLANGE COM', 'CANO COMBUSTIVEL', 'PORCA TAMPA BOMBA COMB']},
            'flanges_combustivel': {'codigo': '0089', 'itens': ["ADAPTADOR FLANGE CAIXA", "FLANGE", 'FLANGE COMBUSTIVEL', 'FLANGE MODULO COMBUSTIVEL']},
            'tanque_combustivel': {'codigo': '0151', 'itens': ['TANQUE COMBUSTIVEL']},
        }
    },
    'correias': {
        'codigo': '0023',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CORREIA VENTOINHA', 'KIT CORREIA E TENSOR', 'PARAFUSO TENSOR CORREIA']},
            'correias_dentadas': {'codigo': '0023', 'itens': ['CORREIA COMANDO', 'CORREIA DENTADA', 'KIT CORREIA COM', 'KIT CORREIA COMANDO']},
            'correias_polyv': {'codigo': '0024', 'itens': ['CORREIA ALT', 'CORREIA ALTERNADOR', 'CORREIA AR COND', 'CORREIA MICRO V', 'CORREIA POLY V', 'CORREIA MULTI V', 'KIT CORREIA VIRABREQUIM']},
            'correias_em_v': {'codigo': '0119', 'itens': ['CORREIA EM V', 'CORREIA EM V AR COND', 'CORREIA EM V ALT']},
        }
    },
    'direcao': {
        'codigo': '0024',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ADAPTADOR VOLANTE", 'BORRACHA FIXADORA CAIXA DIRE', 'BORRACHA FIXACAO SETOR', 'PARAFUSO FIXO TUBO DIRECAO', 'PARAFUSO PORCA PIVO', 'PORCA CASTELO RODA', 'PORCA CUBO', 'PORCA RODA', 'PORCA ENCOSTO', 'PORCA PONTO EIXO', 'PORCA RODA', 'CHAVETA EIXO']},
            'buchas_direcao': {'codigo': '0102', 'itens': ["BUCHA COLUNA DIRECAO", 'BUCHA SETOR DIRECAO', 'BUCHA BRACO', 'BUCHA INF BRACO', 'BUCHA CAIXA DIRECAO', 'BUCHA COLUNA DIRECAO', 'BUCHA CAIXA DIRECAO', 'BUCHA FIX SETOR DIRECAO', 'BUCHA NUCLEO ARTIC', 'BUCHA TERMINAL DIRECAO']},
            'bombas_direcao': {'codigo': '0099', 'itens': ['BOMBA DIRECAO HIDRAULICA', 'BOMBA HIDRAULICA']},
            'caixas_direcao': {'codigo': '0025', 'itens': []},
            'coifas_direcao': {'codigo': '0128', 'itens': ['KIT COIFA SETOR']},
            'setor_direcao': {'codigo': '0026', 'itens': ['SETOR DIRECAO']},
            'barras_axiais': {'codigo': '0027', 'itens': ['BARRA AXIAL', 'BARRA BRACO TENSOR', 'BARRA DIRECAO', 'BARRA LATERAL', 'BRACO AUXILIAR', 'BRACO DIANT INF', 'BRACO OSCILANT', 'BRACO PITMAN', 'BRACO SETOR', 'BRACO SUSP', 'BRACO TENSOR', 'SUPORTE BRACO TENSOR']},
            'pivos': {'codigo': '0067', 'itens': ['PIVO', 'PIVO INFERIOR', 'PIVO', 'PIVO SUSP', 'KIT PIVO SUSP']},
            'terminal_direcao': {'codigo': '0093', 'itens': ['TERMINAL DIR', 'TERMINAL DIRECAO', 'TERMINAL SUSPENSAO', 'TERMINAL BARRA DIRECAO']},
            'colunas_direcao': {'codigo': '0124', 'itens': ['COLUNA DIR', 'COLUNA DIRECAO', 'JUNCAO COLUNA DIRECAO']},
            'cubos_direcao': {'codigo': '0126', 'itens': ['CUBO DIRECAO', 'CUBO VOLANTE']},
        }
    },
    'filtros': {
        'codigo': '0025',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['FILTRO DAGUA', 'FILTRO HIDRAULICO']},
            'filtros_ar': {'codigo': '0028', 'itens': ['FILTRO AR', 'FILTRO CARBURADOR']},
            'filtros_combustivel': {'codigo': '0029', 'itens': ['FILTRO BOMB COMB', 'FILTRO COMBUSTIVEL', 'FILTRO DIESEL', 'FILTRO CANISTER', 'FILTRO SEDIMENTADOR', 'PRE FILTRO', 'PRE FILTRO BOMBA COMB', 'PRE FILTRO COMB']},
            'filtros_de_oleo': {'codigo': '0030', 'itens': ['FILTRO OLEO', 'FILTRO DE OLEO', 'FILTRO RETORNO']},
            'filtros_de_ar_condicionado': {'codigo': '0074', 'itens': ['FILTRO AR CONDICIONADO']},
            'filtros_de_cabine': {'codigo': '0075', 'itens': []},
            'filtros_cambio': {'codigo': '0130', 'itens': ['FILTRO CAIXA AUTOMATICA', 'FILTRO CAMB', 'FILTRO CAMBIO', ]}
        }
    },
    'freios': {
        'codigo': '0026',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ACIONADOR FREIO", "ACIONADOR/GATILHO FREIO", 'JUNCAO GUIA CABO FREIO', 'KIT FREIO', 'PARAFUSO SANGRADOR', 'PRATO FREIO' ]},
            'pastilhas_freio': {'codigo': '0031', 'itens': ['PASTILHA FREIO', 'PASTILHA FREIO DIANT', 'PASTILHA FREIO DIANTEIRO', 'PASTILHA FREIO TRASEIRO', 'PASTILHA FREIO TRAS', 'PASTILHA TRAS']},
            'coifas_freio': {'codigo': '0128', 'itens': ['COIFA FREIO']},
            'canos_freio': {'codigo': '0116', 'itens': ['CANO DE FREIO', 'CANO FREIO']},
            'discos_freio': {'codigo': '0032', 'itens': ['DISCO FREIO', 'DISCO FREIO DIANT', "DISCO FREIO TRAS"]},
            'tambores_freio': {'codigo': '0033', 'itens': ['TAMBOR FREIO', 'TAMBOR FREIO TRASEIRO', 'TAMBOR ']},
            'flexiveis_freio': {'codigo': '0034', 'itens': ['BIFURCACAO AO FLEXIVEL', 'FLEXIVEL', 'FLEXIVEL FREIO', 'FLEX DIANT', 'FLEXIVEL TRAS', 'FLEXIVEL FREIO DISCO', 'FLEXIVEL TRAS']},
            'pincas_freio': {'codigo': '0035', 'itens': ['PINCA FREIO']},
            'cilindros_roda_freio': {'codigo': '0036', 'itens': ['CILINDRO RODA']},
            'cilindros_mestre_freio': {'codigo': '0037', 'itens': ['CILINDRO MESTRE', 'CILINDRO MESTRE FREIO']},
            'lonas_freio': {'codigo': '0038', 'itens': ['LONA', 'LONA FREIO', 'LONA FREIO TRAS']},
            'sapatas_freio': {'codigo': '0039', 'itens': ['PATIM', 'PATIM SAPATA FREIO']},
            'servo_freios': {'codigo': '0087', 'itens': ["ACIONADOR FREIO", "ALAVANCA ACIONAMENTO FREIO", "GATILHO FREIO", 'SERVO FREIO', 'SERVO FREIO BENDIX', 'SERVO FREIO REMANUFATURADO']},
        }
    },    
    'juntas_retentores': {
        'codigo': '0027',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['JUNTA BOMBA COMBUS', 'JUNTA SENSOR TEMP', 'JUNTA BASE CARBURADOR', 'JUNTA CONEXAO SENSOR TEMPERATURA', 'JUNTA CONEXAO SENSOR TEMPERATURA', 'JUNTA CURTICA', 'JUNTA LUBRIFICACAO', 'JUNTA RADIADOR', 'JUNTA TAMPA BOMBA', 'JUNTA TAMPA ARVORE', 'JUNTA TAMPA DIFERENCIAL', 'JUNTA TAMPA OLEO', 'JUNTA TAMPA TRAS', 'JUNTA SUPERIOR FILTRO OLEO', 'JUNTA SUPORTE ROLAMENTO', 'JUNTA VELUMOIDE', 'KIT JUNTA RADIADOR', 'RETENTOR BOMBA HIDRAULICA', 'RETENTOR BOMBA INJETORA', 'RETENTOR SELO COMPRESSOR', 'VELUMOIDE JUNTAS']},
            'aneis': {'codigo': '0091', 'itens': ['ANEIS PISTAO', 'ANEL PISTAO', 'ANEL BUJAO', 'ANEL AJUSTE ROLAMENTO', 'ANEL ALAVANCA', 'ANEL AMORTECEDOR', 'ANEL ANTI RUIDO', 'ANEL BOCAL TANQUE', 'ANEL BORRACHA', 'ANEL BRACO SUSP', 'ANEL CARCACA', 'ANEL CEBOLAO', 'ANEL CILINDRO', 'ANEL COLETOR', 'ANEL VEDACAO', 'ANEL EIXO TRAS', 'ANEL IMPULSOR ARV', 'ANEL INFERIOR CARRO', 'ANEL INTERMEDIARIO', 'ANEL JUNTA', 'ANEL MALHA ACO', 'ANEL MOTOR', 'ANEL RADIADOR', 'ANEL RODA', 'ANEL SILENCIOSO', 'ANEL SINCRONIZ', 'ANEL TAMPA VALV', 'ANEL TIRANTE SUSP', 'ANEL TRASEIRO', 'ANEL TRAVA', 'ANEL VEDACAO', 'ANEL VEDADOR', 'ANEL JUNTA DISTRI', 'ANEL TOMADA FORCA', 'BORRACHA BOCAL', 'GARFO ANEL', 'ANEL ESCAPAMENTO']},
            'diafragmas_tampa': {'codigo': '0127', 'itens': ['DIAFRAGMA TAMPA VALVU']},  
            'jogo_juntas': {'codigo': '0133', 'itens': ['JOGO JUNTA', 'JUNTA COMPLETA RETENTOR']},  
            'juntas_bombas_agua': {'codigo': '0143', 'itens': ['JUNTA BASE BOMBA AGUA', 'JUNTA BOMBA AGUA', 'JUNTA CONEXAO BOMBA AGUA']},  
            'juntas_cabecote': {'codigo': '0040', 'itens': ['JUNTA CABECOTE', 'JUNTA CABE', 'JUNTA FLANGE CABE', 'JUNTA INF CABEC']},
            'juntas_coletor': {'codigo': '0041', 'itens': ['JUNTA COLETOR', 'JUNTA COL', 'JUNTA CONECTOR COLETOR ADM']},
            'juntas_cambio': {'codigo': '0134', 'itens': ['JUNTA CAMBIO', 'JUNTA CAIXA', 'JUNTA DIFERENCIAL', 'JUNTA EIXO DIANT', 'KIT MANCA CAIXA']},
            'juntas_carburador': {'codigo': '0135', 'itens': ['JUNTA CARBURADOR', 'KIT JUNTA CARB', 'KIT JUNTA CARBURADOR']},
            'juntas_carter': {'codigo': '0042', 'itens': ['JUNTA CARTER', 'JUNTA INFERIOR CART', 'KIT TAMPA CARTER']},
            'juntas_escapamento': {'codigo': '0136', 'itens': ['JUNTA CATALISADOR', 'JUNTA COLETOR ESC', 'JUNTA COLETOR ESCAPAMENTO', 'JUNTA ENTRADA COLETOR', 'JUNTA ESCAP', 'JUNTA ESCAPAMENTO', 'JUNTA ESCAPE', 'JUNTA SAIDA ESCAP', 'KIT JUNTA COLETOR ESCAP']},
            'juntas_injecao': {'codigo': '0137', 'itens': ['JUNTA INJ', 'JUNTA INJECAO', 'KIT JUNTA INJECAO']},
            'juntas_motor': {'codigo': '0138', 'itens': ['JUNTA MOTOR', 'JUNTA RETIFI', 'JUNTA RETIFICA', 'JUNTA SUPERIOR MOTOR']},
            'juntas_tampa_valvula': {'codigo': '0043', 'itens': ['JUNTA TAMPA VALVULA', 'JUNTA INTERM TAMPA VALV', 'JUNTA RETENTOR ANEL TAMPA''JUNTA TAMP VALV', 'KIT JUNTA TAMPA VALV']},
            'juntas_tampa_distribuidor': {'codigo': '0044', 'itens': ['JUNTA TAMPA DIST']}, 
            'retentores_eixo': {'codigo': '0045', 'itens': ['RETENTOR CAIXA DIRECAO', 'RETENTOR CUBO RODA', 'RETENTOR EIXO', 'RETENTOR EXTERNO RODA', 'RETENTOR INTERNO RODA', 'RETENTOR PINO MESTRE', 'RETENTOR POLIA', 'RETENTOR RODA DIANT', 'RETENTOR RODA EIXO', 'RETENTOR RODA TRAS', 'RETENTOR SEMI EIXO', 'RETENTOR VOLANTE']},
            'retentores_virabrequim': {'codigo': '0046', 'itens': ['RETENTOR DIANT VIRABREQUIM', 'RETENTOR VIRABREQUIM']},
            'retentores_comando_valvula': {'codigo': '0047', 'itens': ['RETENTOR VALVULA ADMISSAO', 'RETENTOR VALVULA', 'KIT RETENTOR COMANDO VALVULA', 'RETENTOR ARVORE', 'RETENTOR COIFA DIRECIONAL', 'RETENTOR COMANDO', 'RETENTOR HASTE VALVULA', 'RETENTOR SEMI ARVORE']},
            'retentores_caixa_cambio': {'codigo': '0048', 'itens': ['RETENTOR CAIXA CAMBIO', 'RETENTOR CAIXA TRACAO', 'RETENTOR CAIXA TRACAO', 'RETENTOR CAMBIO SEMI EIXO', 'RETENTOR CAMBIO', 'RETENTOR COROA LATERAL', 'RETENTOR DIFERENCIAL', 'RETENTOR PINHAO', 'RETENTOR RABETA', 'RETENTOR SAIDA CAMBIO', 'RETENTOR SAIDA CAIXA', 'RETENTOR SAIDA DIFERENCIAL', 'RETENTOR TAMPA LATERAL CAMBIO', 'RETENTOR TRAMBULADOR', 'RETENTOR TRANSMISSAO']},
            'retentores_motor': {'codigo': '0141', 'itens': ['KIT RETENTOR MOTOR', 'RETENTOR BOMBA INJETORA', 'RETENTOR BOMBA VACUO', 'RETENTOR MANCAL ALTERNADOR', 'RETENTOR CAIXA MOTOR', 'RETENTOR POLIA MOTOR', 'RETENTOR MOTOR', 'RENTENTO DIAT COMANDO', 'RETENTOR DISTRIBUIDOR', 'RETENTOR CORREIA ']},
            'vedacao': {'codigo': '0114', 'itens': ["BUCHA VEDACAO", 'GUARNICAO BUCHA VEDACAO', 'GUARNICAO', 'JUNTA BOIA COMB', 'JUNTA GUARNICAO', 'KIT PESCOCEIRA', 'KIT SELO COMANDO', 'KIT VEDACAO FLANGE', 'SELO AGUA=', 'SELO MOTOR', 'SELO BLOCO MOTOR', 'TAMPA', 'TAMPA MANCAL', 'TAMPA AR QUENTE', 'TAMPA BLOCO CABECOTE', 'TAMPA BOMBA COMBUSTIVEL', 'TAMPA TORCAO', 'TAMPA CAIXA AR', 'TAMPA CAIXA FILTRO AR', 'TAMPA CORRENTE MOTOR', 'TAMPA DIAFRAGMA CARBURADOR', 'TAMPA DIAFRAGMA REGULADOR', 'TAMPA DIANT BLOCO', 'TAMPA DISTRIB', 'TAMPA CARBUR', 'TAMPA FILTRO OLEO', 'TAMPA HOMO MOTOR', 'TAMPA BLOCO MOTOR', 'TAMPA MOTORES', 'TAMPA MOTRIZ PASSAT', 'TAMPA OLEO', 'TAMPA RADIADOR', 'TAMPA REGULAGEM FREIO', 'TAMPA RESERV AGUA', 'TAMPA RESERV GASOLINA', 'TAMPA RESERV LIMPADOR', 'TAMPA RESERV LIQ FREIO', 'TAMPA RESERV UNIVERSAL', 'TAMPA RESERVATORIO AGUA', 'TAMPA RESERVATORIO EXPANSAO', 'TAMPA RESERVATORIO GASOLINA', 'TAMPA RESERV LIMPADOR', 'TAMPA RESERV PARTIDA FRIO', 'TAMPA RESERVATORIO RADIADOR', 'TAMPA TANQUE', 'TAMPA TANQUE COMBUSTIVEL', 'TAMPA VALV', 'TAMPA VALVULA MOTOR', 'TAMPA DINAMO', 'TAMPA VENTIL', 'TAMPAO LATAO', 'TAMPAO BOMBA AGUA', 'TAMPAO CARC VALV', 'TAMPAO MACHO ROSCA', 'TAPA PO CAIXA', 'VEDACAO JUNTA', 'VEDACAO MONOPONTO', 'VEDADOR BRACO', 'VEDADOR HASTE', 'VEDADOR RADIADOR', ]},
        }
    },
    'lubrificacao': {
        'codigo': '0028',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ALONGADOR VARETA', 'FLEXIVEL FILTRO OLEO', 'PESCADOR BOMBA OLEO', 'PESCADOR CARTER OLEO', 'RESPIRO OLEO']},
            'bombas_oleo': {'codigo': '0049', 'itens': ['BOMBA OLEO', 'CORPO BOMBA OLEO']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM BOMBA OLEO']},
            'reservatorios_oleo': {'codigo': '0050', 'itens': []},
            'vareta_oleo': {'codigo': '0155', 'itens': ['VARETA OLEO', 'VARETA NIVEL OLEO']},
        }
    },
    'mangueiras': {
        'codigo': '0029',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['MANGEIRA TAMPA VALV CONEXAO', 'MANGUEIRA DIRECAO HIDR', 'PRESIL']},
            'mangueiras_ar_condicionado': {'codigo': '0051', 'itens': ['MANGUEIRA AR COND', 'MANGUEIRA AR CONDICIONADO', 'MANGUEIRA EVAPORADOR AR COND', 'MANGUEIRA AQUECEDOR AR COND']},
            'mangueiras_aquecimento': {'codigo': '0052', 'itens': ['MANGUEIRA AQUECEDOR', 'MANGUEIRA AQUECIMENTO', 'MANGUEIRA ENTR AQUECEDOR', 'MANGUEIRA ENTRADA AQUEC', 'MANGUEIRA ENTRADA AQUECEDOR', 'MANGUEIRA ENTRADA AQUECIMENTO', 'MANGUEIRA PRE AQUEC', 'MANGUEIRA SAIDA AQUEC', 'MANGUEIRA TUBO AQUEC', 'MANGUEIRA VALV AQUECIMENTO']},
            'mangueiras_carcacas': {'codigo': '0146', 'itens': ['MANGUEIRA ANTI CHAMA', 'MANGUEIRA CARCACA', 'MANGUEIRA CORPO VALV TERMOSTATICA', 'MANGUEIRA ENTRADA AR CHAMA', 'MANGUEIRA COLETOR ANTI CHAMA', 'MANGUEIRA COLETOR CHAMA', 'MANGUEIRA COLETOR VALV TERMOSTATICA', 'MANGUEIRA RESPIRO ANTI CHA', 'MANGUEIRA VALV TERMOST', 'MANGUEIRA VALV REG PRESSAO ANTI CHAMA']},
            'mangueiras_combustivel': {'codigo': '0053', 'itens': ['MANGUEIRA BOCAL COMB', 'MANGUEIRA BOCAL TANQUE', 'MANGUEIRA BOMBA INJ COMB', 'MANGUEIRA BOMBA LIGACAO BICO INJETOR', 'MANGUEIRA COMBUSTIVEL', 'MANGUEIRA ELETROVALVULA', 'MANGUEIRA CANISTER', 'MANGUEIRA COLETOR', 'MANGUEIRA RETORNO']},
            'mangueiras_agua': {'codigo': '0054', 'itens': ['MANGUEIRA AGUA AQUECEDOR', 'MANGUEIRA AGUA MOTOR', 'MANGUEIRA AGUA QUENTE', 'MANGUEIRA ALIMENTACAO AGUA', 'MANGUEIRA RESERV', 'MANGUEIRA RESERV AGUA', 'MANGUEIRA BOMBA AGUA', 'MANGUEIRA BOMBA DAGUA', 'MANGUEIRA BOMBA HIDR', 'MANGUEIRA DAGUA', 'MANGUEIRA DUTO RIGIDO BOMBA AGUA', 'MANGUEIRA ENTRADA AGUA AQUECIMENTO', 'MANGUEIRA ENTRADA BOMBA AGUA', 'MANGUEIRA ENTRADA AGUA', 'MANGUEIRO ENVIO DAGUA', 'MANGUEIRA FLUXO AGUA', 'MANGUEIRA HIDRAULICO', 'MANGUEIRA LIGACAO BOMBA AGUA', 'MANGUEIRA LIGACAO AGUA', 'MANGUEIRA RETORNO AGUA', 'MANGUEIRA SAIDA AGUA', 'MANGUEIRA ARREFECIMENTO', 'MANGUEIRA BOMBA CABECOTE', 'MANGUEIRA BOMBA TUBO REFRIGERA', 'MANGUEIRA COLETOR AGUA', 'MANGUEIRA COLETOR DUTO', 'MANGUEIRA COLETOR TUBO AGUA', 'MANGUEIRA CURVA SUP RADIADOR', 'MANGUEIRA EXPANSAO RADIADOR', 'MANGUEIRA DESCARGA', 'MANGUEIRA RADIADOR', 'MANGUEIRA TERMOSTATO', 'MANGUEIRA DRENO', 'MANGUEIRA DUTO RADIADOR', 'MANGUEIRA ENTRADA TUBO REFRIGERACAO', 'MANGUEIRA FLANGE AO RADIADOR', 'MANGUEIRA INFERIOR', 'MANGUEIRA INF RADIADOR', 'MANGUEIRA INFERIOR RADIADOR', 'MANGUEIRA SUP RADIADOR', 'MANGUEIRA SUPERIOR', 'MANGUEIRA SUPERIOR RADIADOR', 'MANGUEIRA TORNEIRA', 'MANGUEIRA TUBO BOMBA AGUA', 'MANGUEIRA TUBO CAMARA TERMOST', 'MANGUEIRA TUBO CURVO SUP RADIADOR', 'MANGUEIRA TUBO DAGUA', 'MANGUEIRA TUBO REFRIG', 'MANGUEIRA TUBO RESERVATORIO', 'MANGUEIRA TUBO RESFRIADOR', 'MANGUEIRA TUBO RETORNO AGUA', 'MANGUEIRA TUBO CONEX AGUA', 'MANGUEIRA VALV TERMOST AGUA']},
            'mangueiras_ar_motor': {'codigo': '0085', 'itens': ['DUTO FILTRO AR', 'MANGUEIRA FILTRO AR', 'DUTO AR ADMISSAO', 'KIT MANGUEIRA AR QUENTE', 'MANGUEIRA ADAPTACAO VALV', 'MANGUEIRA ADMISSAO', 'MANGUEIRA AR QUENTE', 'MANGUEIRA COLETOR ADM', 'MANGUEIRA COLETOR ADMISSAO', 'MANGUEIRA CONECTOR AQUEC', 'MANGUEIRA FILTRO AR', 'MANGUEIRA DUTO FILTRO', 'MANGUEIRA DUTO RIGIDO COLETOR', 'MANGUEIRA AR QUENTE', 'MANGUEIRA FILTRO COLETOR', 'MANGUEIRA FITRO AR', 'MANGUEIRA LIGACAO COLETOR ADMISSAO', 'MANGUEIRA RESPIRO MOTOR', 'MANGUEIRA LIGACAO VALV COLETOR', 'MANGUEIRA MOTOR AR QUENTE' ,'MANGUEIRA RESPIRO', 'MANGUEIRA RETORNO AR', 'MANGUEIRA RETORNO TURBO', 'MANGUEIRA SAIDA AR', 'MANGUEIRA SISTEMA AR', 'MANGUEIRA ADMISSAO BOMBA', 'MANGUEIRA BOMBA VACUO', 'MANGUEIRA CABECOTE CARBURADOR', 'MANGUEIRA CARBURADOR', 'MANGUEIRA COLETOR ADMISSAO OLEO', 'MANGUEIRA COLETOR ADMISSAO', 'MANGUEIRA COLETOR ADMISSAO AGUA', 'MANGUEIRA COLETOR CABECOTE', 'MANGUEIRA COLETOR CONEXAO', 'MANGUEIRA AR COLETOR', 'MANGUEIRA TUBO COLETOR', 'MANGUEIRA COMPENSACAO MARCHA LENT', 'MANGUEIRA CONJUNTO MENOR', 'MANGUEIRA DO INTERCOOLER TURBO', 'MANGUEIRA ENTRADA DISTRIBUICAO', 'MANGUEIRA SERVO FREIO', 'MANGUEIRA RESPIRO MOTOR', 'MANGUEIRA TUBO LIGAC SENSOR PALIO', 'MANGUEIRA TUBO VENTILACAO MOTOR', 'MANGUEIRA TURBO RESFRIADOR', 'MANGUEIRO FILTRO AO EXAUSTOR', 'MANGUEIRA TUBO DIANTEIRO', 'MANGUEIRA VACUO', 'MANGUEIRA VALVULA AR', 'MANGUEIRA VALVULA VAPOR', 'MANGUEIRA VALV RESPIRO', 'MANGUEIRA VENT', 'MANGUEIRA VENT BLOCO', 'MANGUEIRA VENTILACAO', 'MANGUEIRA VENTILACAO MOTOR', 'MANGUEIRA VENTILADOR']},
            'mangueiras_oleo': {'codigo': '0086', 'itens': ['MANGUEIRA BLOCO OLEO', 'MANGUEIRA RESPIRO OLEO', 'MANGUEIRA LUBRIFICACAO BOMBA DIRECAO', 'MANGUEIRA RETORNO OLEO', 'MANGUEIRA FILTRO OLEO', 'MANGUEIRA ENTRE TUBO E RADIADOR OLEO', 'MANGUEIRA LIGACAO CABECOTE', 'MANGUEIRA RAD OLEO', 'MANGUEIRA RESFRIADOR OLEO', 'MANGUEIRA RESFRIAMENTO COLETOR', 'MANGUEIRA RESFRIAMENTO OLEO', 'MANGUEIRA RESPIRO OLEO', 'MANGUEIRA TAMP VALV', 'MANGUEIRA TUBO RADIADOR OLEO']},
            'mangueiras_metro': {'codigo': '0145', 'itens': ['MANGUEIRA METRO', 'MANGUEIRA METRO COMBUSTIVEL']},
            'bocais': {'codigo': '0097', 'itens': ['BOCAL TANQUE']},
        }
    },    
    'motor': {
        'codigo': '0030',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BUCHA ARRANQUE', 'BALANCIM', 'DEFLETOR CARTER', 'GARFO PARTIDA', 'GUIA VALVULA', 'KIT MOTOR', 'PULA MACACO', 'PARAFUSO CABECOTE', 'PARAFUSO COLETOR ADMISSAO', 'PARAFUSO COM PORCA MOTOR', 'PARAFUSO MOTOR', 'PARAFUSO TAMPA VALV', 'PASTILHA REGULAGEM', 'PENEIRA CARTER', 'PORCA VOLANTE ']},
            'cabecotes': {'codigo': '0055', 'itens': ['CABECOTE', 'CABECOTE MOTOR']},
            'comandos': {'codigo': '0118', 'itens': ['COMANDO', 'EIXO COMANDO', 'GAIOLA COMANDO', 'EIXO COMANDO VALV', 'KIT COMANDO']},
            'coxins': {'codigo': '0078', 'itens': ['COXIM MOTOR', 'COXIM DIANT MOTOR', 'COXIM CENTRAL MOTOR', 'KIT COXIM MOTOR']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM VIRABREQUIM', 'ENGRENAGEM CORPO BORBOLETA']},
            'virabrequins': {'codigo': '0056', 'itens': []},
            'kit_corrente': {'codigo': '0144', 'itens': ['KIT CORRENTE/TENSOR/ENGREN', 'KIT DISTRIB']},
            'carteres': {'codigo': '0057', 'itens': ['CARTER']},
            'bronzinas': {'codigo': '0100', 'itens': ['BRONZINA','BRONZINA DE BIEL', 'BRONZINA MANCAL']},
            'tuchos': {'codigo': '0103', 'itens': ['BUCHA POSTERIOR ARVORE', 'CAPA TUCHO', 'KIT TUCHO VELA', 'TUCHO HIDRAULICO', 'TUCHO VALVULA', 'VARETA TUCHO']},
            'parafuso_cabecote': {'codigo': '0105', 'itens': ['BUCHA PRISIONEIRO CABECOTE', 'JOGO PARAFUSO CABECOTE','PARAFUSO CABECOTE', 'PARAFUSO PRISIONEIRO']},
            'corpo_borboleta': {'codigo': '0123', 'itens': ['CORPO BORBOLETA']},
            'jogo_pistoes': {'codigo': '0142', 'itens': ['JOGO MOTOR PISTAO CAMISA', 'SUPER KIT MOTOR ']},
            'valvulas_motor': {'codigo': '0153', 'itens': ['VALVULA ADMISSAO', 'VALVULA ESCAPAMENTO', 'VALVULA ESCAPE', 'VALVULA FILTRO AR', 'VALVULA MAXIMA CARB', 'VALVULA MOTOR ESCAP', 'VALVULA RESPIRO MOTOR', 'VALVULA RESPIRO TANQUE', 'VALVULA TERMOSTATICA', 'VALVULA ADMISSAO']},
        }
    },
    'reparos': {
        'codigo': '0031',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ACOPLAMENTO COLETOR ADMISSAO", "ACOPLAMENTO DIRECAO", "ACOPLAMENTO VISOCOSO", 'ADAPTADOR BICO INJETOR', "ADAPTADOR COLETOR ADMISSAO", "REPARO COLETOR ADMISSAO", "REPARO DIRECAO", "ADAPTADOR MOTOR MAQ VIDRO", 'BUCHA RETORNO PEDAL', 'EIXO ACELERADOR', 'ENGRENAGEM LIMP PARABR', 'FILTRO BICO ANE', 'JOGO MOLA TRAS BENDIX', 'KIT BUCHA VEDACAO', 'KIT BUCHA MOTOR', 'KIT CALCO MOLA', 'KIT CALOTA CUBO', 'KIT PINO GUIA VOLANTE', 'KIT REPARO BIELETA', 'KIT REPARO COLUNA DIRECAO', 'KIT REPARO CREMALHEIRA', 'KIT REPARO FEIXE MOLA', 'KIT REPARO SETOR', 'KIT REPARO ROLAMENTO', 'KIT ROLAMENTO REPARO BANDEJA', 'KIT SUSPENSAO TRAS', 'PINHAO VELOCIMETRO', 'PINO PEDAL EMBREAGEM', 'PINO ELAST ALAVANCA CAMB', 'PINO FIXACAO HASTE', 'PINO PASTILHA', 'PINO PEDAL', 'PINO TRAVA ALAVANCA CAMBIO', 'PINO TRAVA HASTE', 'PINO TRAVA TRAMBULADOR', 'PINO TULIPA', 'REPARO AMORTECEDOR', 'REPARO BOMBA AGUA', 'REPARO CARBURADOR', 'REPARO VEDACAO CAVALETE', 'SEPARADOR FEIXE MOLA', 'TRAVA CABO COMANDO', 'TRAVA BOIA COMB', 'TRAVA COXIM ESCAP', 'TRAVA PASTILHA', 'TRAVA PIVO', 'TRAVA ROLAMENTO', 'TRAVA VEDACAO', 'TRAVA ABRACADEIRA PIVO']},
            'kit_reparo_aneis': {'codigo': '0139', 'itens': ['KIT ANEIS', 'KIT ANEL', 'KIT ARRUELA EMBUCHAMENTO', 'REPARO ANEL']},
            'kit_reparo_cambio': {'codigo': '0059', 'itens': ['ACOPLAMENTO HASTE TRAMBULADOR', 'ACOPLAMENTO HASTE LIGACAO',"ACOPLAMENTO VARAO CAMBIO", 'ARTICULACAO CABO ENGATE', 'ARTICULADOR CABO ENGATE', 'LIAME TRAMB', "REPARO VARAO CAMBIO", 'BUCHA ALAVANCA CAMBIO', 'BUCHA REPARO ALAVANCA', 'BORRACHA/REPARO TRAMBULADOR', 'CACHORRINHO REPARO ANEIS', 'BUCHA CABO MARCHA', 'BUCHA PEDAL EMBREAGEM', 'BUCHA PRETA TRAMBULADOR', 'BUCHA SELETOR MARCHA', 'BUCHA TRAMBULADOR', 'BUCHA VARAO CAMBIO', 'CONJUNTO KIT REPARO PEDAL', 'CATRACA ACIONADOR EMBREAGEM', 'CONJUNTO AGULHA MOLA MARCHA', 'COROA VELOCIMETRO', 'EIXO PINHAO VELOCIMETRO', 'ENGATE TRAMBULADOR', 'KIT ARTICULADOR MARCHA', 'KIT BUCHA TRAMBULADOR', 'KIT HASTE SELETORA', 'KIT PEDAL ACELERADOR', 'KIT PINO MOLA CAMBIO', 'KIT REPARO ARTICULACAO TRAMB', 'KIT REPARO CABO CAMBIO', 'KIT REPARO CABO COMANDO', 'KIT REPARO CABO EMBREAGEM', 'KIT REPARO GARFO EMBREAGEM', 'KIT REPARO HOMOCINETICA', 'KIT REPARO JUNTA HOMOCI', 'KIT REPARO TRAMBULADOR', 'KIT SETOR CAIXA', 'KIT SUPORTE TRAMBULADOR', 'KIT TENSOR DIANT', 'KIT TENSOR SUSP', 'KIT SUPORTE TRAMBULADOR', 'KIT TRAMBULADOR', 'LIMITADOR TORCAO', 'PEDAL ACELERADOR', 'KIT COROA PINHAO', 'PINHAO COROA', 'PLANETARIA', 'REPARO BARRA TORCAO', 'REPARO CABO CAMBIO', 'REPARO CABO EMBREAGEM', 'REPARO CAIXA DIFERENCIAL', 'REPARO DIFERENCIAL', 'REPARO PLANETARIO', 'REPARO TRAMBULADOR', 'REPARO TRIZETA', 'SUB CONJUNTO TRAMBULADOR', 'TIRANTE ACIONAMENTO EMBREAGEM', 'TIRANTE COMANDO CAMBIO', 'TRAMBULADOR']},
            'kit_reparo_freio': {'codigo': '0140', 'itens': ['KIT REGULADOR DO FREIO', 'JOGO MOLA FREIO', 'JOGO REGULADOR FREIO', 'KIT PISTAO FREIO', 'KIT REPARO PATIM', 'KIT REPARO SAPATA', 'KIT EMBUCHAMENTO', 'REGULADOR FREIO', 'REGULADOR PATIM', 'REPARO CENTRAL PATIM', 'REPARO FREIO DIANT', 'REPARO FREIO', 'REPARO PATIM', 'REPARO PEDAL FREIO', 'REPARO SAPATA', 'REPARO VALV SERVO FREIO']},
            'kit_reparo_eletrica': {'codigo': '0205', 'itens': ['KIT REPARO BICO INJETOR', 'REPARO AUTOMATICO PARTIDA' , 'REPARO BICO INJETOR', 'REPARO FLAUTA INJETOR', 'REPARO INJETOR', 'REPARO MOTOR PARTIDA', 'REPARO PARTIDA PORTA ESCOVA', 'REPARO PRESSAO']},
            'kit_reparo_homocinetica': {'codigo': '0058', 'itens': ['KIT REPARO HOMOCINETICA']},
            'kit_reparo_pincas': {'codigo': '0077', 'itens': ['BUCHA PINCA', 'KIT PINO PINCA', 'REPARO PINCA', 'REPARO PINCA FREIO', 'REPARO PINCA VEDACAO']},
            'kit_reparo_setor': {'codigo': '0088', 'itens': ['ACOPLAMENTO SETOR', 'GUIA SETOR DIRECAO', 'REPARO COLUNA DIR', 'REPARO CIL RODA', 'REPARO CILINDRO MESTRE', 'REPARO CILINDRO RODA', 'REPARO COLUNA', 'REPARO PARCIAL CIL RODA', 'REPARO SETOR']},
            'kit_reparo_suspensao': {'codigo': '0148', 'itens': ['REPARO BANDEJ', 'REPARO BANDEJ EIXO', 'REPARO BATENTE BANDEJ', 'REPARO BRACO OSCILANTE', 'REPARO CAPA EIXO', 'REPARO EIXO TRAS']},
            'alavancas': {'codigo': '0090', 'itens': ['ALAVANCA ACIONADORA', 'ALAVANCA CAMBIO', 'ALAVANCA EMB', 'ALAVANCA EMBREAGEM', 'ALAVANCA ENGATE', 'ALAVANCA ENGRENAGEM', 'ALAVANCA FREIO MAO', 'ALAVANCA FREIO TRAS', 'ALAVANCA INIBIDORA', 'ALAVANCA LIGACAO', 'ALAVANCA MARCHA', 'ALAVANCA PATIM', 'ALAVANCA REG', 'ALAVANCA REGULADO', 'ALAVANCA SELETORA', 'ALAVANCA TRAMBULADOR', 'BUCHA LATERAL ALAVANCA', 'HASTE CABO EMB', 'HASTE DESLIZ MARCH', 'HASTE DELIZ RE', 'HASTE ALAV CAMB', 'HASTE EMB', 'HASTE PORSCHE', 'HASTE TRAMB', 'HASTE PATIM FREIO', 'JOGO ALAVANCA ACIONAMENTO', 'KIT ALAVANCA ACELERADOR', 'KIT ALAVANCA CAMBIO', 'KIT ALAVANCA CARBU', 'KIT REPARO ALAVANCA', 'KIR REPARO CUPULA ALAVANCA', 'LIMITADOR ALAVANCA', 'MOLA ALAVANCA SELETORA', 'MOLA ALAVANCA CAMBIO', 'REPARO ALAVANCA CAMBIO', 'REPARO ALAVANCA FREIO', 'REPARO BUCHA VARAO', 'REPARO HASTE ALAVANCA', 'ROTULA ALAVANCA CAMBIO', 'TIRANTE EXTERNO CAMBIO', 'TIRANTE LIGACAO ARTICULACAO', 'TIRANTE LIGACAO CAMBIO', 'TIRANTE SUSP TRAS', 'TRAVA ALAVANCA CAMBIO ', 'VARAO EMBREAGEM']},
            'molas_reparo': {'codigo': '0147', 'itens': ['MOLA EXTERNA VALVULA', 'MOLA ATUACAO VALVULA PROPO FREIO', 'MOLA RETORNO FREIO', 'MOLA COLAR EMBREAGEM', 'MOLA BUZINA', 'MOLA RETENCAO', 'MOLA RETORNO', 'MOLA PATIM', 'MOLA HASTE ACIONAMENTO', 'MOLA INTERNA VALVULA', 'MOLA VALVULA']},
            'valvulas_reparo': {'codigo': '0154', 'itens': ['VALVULA AGULHA', 'VALVULA ALIVIO PRESSAO', 'VALVULA ANTI CHAMA', 'VALVULA AR QUENTE', 'VALVULA OLEO', 'VALVULA EQUALIZADORA', 'VALVULA PROPORCIONADORA', 'VALVULA SERVO FREIO', 'VALVULA SOLENOIDE', 'VALVULA CANISTER', 'VALVULA COMUTADORA', 'VALVULA DE MAXIMA']},
        }
    },
    'rolamentos_tensores_polias': {
        'codigo': '0032',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ROLAMENTO CAMBIO', 'BUCHA AGULHA', 'BUCHA AGULIA', 'KIT ROLAMENTO', 'PARAFUSO ROLAM EST CORREIA', 'ROLAMENTO BOMBA AGUA', 'ROLAMENTO DO ROLO CILINDRICO', 'ROLAMENTO PRIZ']},
            'rolamentos_ar_condicionado': {'codigo': '0150', 'itens': ['ROLAMENTO AR CONDICIONADO', 'ROLAMENTO ESTIC AR', 'ROLAMENTO ESTIC CORR AR']},
            'rolamentos_roda': {'codigo': '0061', 'itens': ['BUCHA ROLAMENTO DIRECAO', 'KIT ROLAMENTO RODA TRAS', 'ROLAMENTO QUADRO SUSPENSAO', 'ROLAMENTO EIXO', 'ROLAMENTO SEMI EIXO', 'ROLAMENTO AMORT', 'ROLAMENTO AMORTECEDOR', 'ROLAMENTO CONICO', 'ROLAMENTO COLUNA DIRECAO', 'ROLAMENTO COXIM AMORT', 'ROLAMENTO CUBO DIANT', 'ROLAMENTO DE EIXO', 'ROLAMENTO EIXO', 'ROLAMENTO RODA', 'ROLAMENTO DIANTEIRO', 'ROLAMENTO SUSPENSAO']},
            'rolamentos_motor': {'codigo': '0062', 'itens': ['ROLAMENTO ESTICADOR', 'ROLAMENTO MOTOR', 'ROLAMENTO ALTERNADOR', 'ROLAMENTO CORREIA ESTICADORA DO ALTERNADOR', 'ROLAMENTO ESTICADOR', 'ROLAMENTO ESTIC ALT', 'ROLAMENTO ESTIC CORR', 'ROLAMENTO ESTIC', 'ROLAMENTO ESTICADOR CORREIA ALTERNADOR', 'ROLAMENTO ESTICADOR ALTERNADOR', 'ROLAMENTO ESTICADOR CORREIA', 'ROLAMENTO COMANDO', 'ROLAMENTO CORREIA COMANDO', 'ROLAMENTO TENSOR', 'ROLAMENTO TENSOR CORREIA']},
            'rolamentos_embreagem': {'codigo': '0149', 'itens': ['ROLAMENTO EMBREAGEM', 'ROLAMENTO CAMBIO', 'ROLAMENTO CAIXA CAMBIO', 'ROLAMENTO CARDAN', 'ROLAMENTO PINHAO', 'ROLAMENTO AGULHA', 'ROLAMENTO ATUADOR EMBREAGEM', 'ROLAMENTO COIFA', 'ROLAMENTO DIFERENCIAL', 'ROLAMENTO LATERAL COROA CAIXA', 'ROLAMENTO SATELITE', 'ROLAMENTRO TRASEIRO CAIXA', 'ROLAMENTO VISCOSA']},
            'tensores': {'codigo': '0063', 'itens': ['ROLO ROLAMENTO DAMPER', 'TENSOR CORREIA ALTERNADOR', 'TENSOR CORREIA COMANDO', 'TENSOR ESTICADOR']},
            'polias': {'codigo': '0064', 'itens': ['POLIA ALTERNADOR', 'POLIA ALT', 'POLIA AUXILIAR', 'POLIA BOMBA AGUA', 'POLIA BOMBA DIR', 'POLIA CORREIA', 'POLIA DIRECAO', 'POLIA VENTILADOR', 'POLIA RODA LIVRE', 'POLIA TENSOR', 'POLIA VIRAB', 'POLIA VIRABREQUIM', 'SOBREPOLIA AR COND']},
        }
    },
    'suspensao': {
        'codigo': '0033',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['EMBUCHAMENTO', 'CALCO AJUSTE', 'CALCO AMORT', 'CALCO BATENT', 'EIXO BANDEJA TRAS', 'EIXO TENSOR', 'ESPACADOR ANEL VEDADOR', 'ESPACADOR ROLAMENTO', 'FACAO SUSPENS', 'MONTANTE', 'PARAFUSO BANDEJA', 'PARAFUSO EIXO TRAS', 'PORCA AMORTECEDOR', 'SUPORTE AMORTECEDOR DIANT', 'TELEFONE PINO ROLAMENTO', 'TIRANTE SUSPENSAO']},
            'buchas_suspensao': {'codigo': '0065', 'itens': ['BARRA TORCAO', 'BUCHA BAND SUSP', 'BUCHA BARRA ESTAB', 'BUCHA BANDEJA DIANT', 'BUCHA AGREGADO', 'BUCHA ALGEMA BARRA', 'BUCHA ALT SUP', 'BUCHA ALTERNADOR', 'BUCHA AMORT', 'BUCHA AMORT DIANT', 'BUCHA AMORTEC', 'BUCHA AMORTECEDOR', 'BUCHA AR COND', 'BUCHA ARTIC EIXO', 'BUCHA ARTICULACAO', 'BUCHA BAND', 'BUCHA BANDEJA', 'BUCHA BARR ESTAB', 'BUCHA BARRA ESTAB', 'BUCHA BARRA LIGACAO', 'BUCHA BARRA TENS SUSP', 'BUCHA BARRA TORCAO' 'BUCHA BIELA', 'BUCHA CALCO TRAVESSA', 'BUCHA CENTRAL BANDEJA', 'BUCHA COXIM', 'BUCHA EIXO', "BUCHA ESTAB", 'BUCHA ESTABILIZADORA', 'BUCHA FEIXE MOLA', 'BUCHA MANGA EIXO', 'BUCHA HAST BAND', 'BUCHA INF AMOR', 'BUCHA INFERIOR BANDE', 'BUCHA INFERIOR AMORT', 'BUCHA INFERIOR JUMELO', 'BUCHA JUMELO', 'BUCHA MAIOR', 'BUCHA MENOR', 'BUCHA MOLA', 'BUCHA OVAL EIXO', 'BUCHA TRAS BAND', 'BUCHA PONTA BANDEJA', 'BUCHA SUP ALGEMA', 'BUCHA SUP AMOR', 'BUCHA SUPERIOR BAND', 'BUCHA SUPERIOR JUMELO', 'BUCHA SUSP', 'BUCHA SUSPEN', 'BUCHA SUSPENSAO', 'BUCHA TENSO', 'BUCHA TENSOR SUS', 'BUCHA TERMINAL EIXO', 'BUCHA TIRANTE', 'BUCHA TARS BAND', 'BUCHA TRAS BRAC', 'BUCHA TRAS EIXO', 'BUCHA TRAS FEIXE MOLA', 'BUCHA TRAS SUSP', 'BUCHA TRAS BAND', 'BUCHA TRASEIRA BANDEJA', 'BUCHA TRAV EIXO', 'BUCHA QUADRO', 'BUCHA SUPERIOR QUADRO', 'BUCHA TRAS QUADRO', 'CAPA AMORTECE DIAN', 'FLUTOBLOC', 'KIT BUCH SUSP', 'KIT BORRACHA BARRA ESTAB', 'KIT BUCHA ACAB', 'KIT BUCHA BARRA ESTAB', 'KIT BUCHA BRACO', 'KIT BUCHA ESTAB', 'KIT BUCHA ESTABILIZADORA', 'KIT BUCHA FEIXE MOLA', 'KIT BUCHA TIRANTE', 'KIT TIRANTE DIANT', 'KIT TIRANTE']},
            'amortecedores': {'codigo': '0066', 'itens': ["AMORT DIANT", "AMORTECEDOR DIANT", "AMORTECEDOR REMAN", "AMORTECEDOR TRAS", "AMORTECEDOR TRASEIRO", 'COXIM COM ROLAMENTO AMORT']},
            'coifas': {'codigo': '0128', 'itens': ['COIFA AMORT', 'GUARDA PO AMORT', 'KIT COIFA AMORT', 'KIT COIFA AMORTECEDOR', 'KIT COIFA BATENTE AMORTECEDOR DIANTEIRO', 'KIT COIFA AMORTECEDOR TRASEIRO', 'KIT COIFA BATENTE DIANTEIRO', 'KIT COIFA BATENTE AMORTECEDOR', 'KIT COIFA BATENTE', 'KIT COIFA BATENTE AMORT', 'KIT COIFA BATENTE DIANTEIRO', 'KIT COIFA BATENTE', 'KIT COIFA BATENTE COXIM AMORT', 'PAR AMORTECEDOR DIANTEIRO', 'PAR AMORTECEDOR REMANUFATURADO' ]},
            'coxins': {'codigo': '0078', 'itens': ['CALCO AMORTECE', 'SEDE ROLAMENTO SUSP', 'COXIM AMORT', 'COXIM AMORTECEDOR', 'COXIM BR OSCI', 'COXIM BRACO OSCIL', ' COXIM CABINE', 'COXIM LIMITADOR TORCAO', 'COXIM ESTABILIZADOR', 'COXIM SUSP', 'CAPA SUSPENSAO', 'COXIM CABINE']},
            'bieletas': {'codigo': '0079', 'itens': ['BIELETA', 'BIELETA BARRA ESTAB', 'BIELETA BARRA ESTABILIZADORA', 'BIELETA DIANT', 'BIELETA ESTAB', 'BIELETA ESTABILIZADORA', 'BIELETA SUSP', 'BIELETA SUSPENSAO', 'BIELETA TRAS']},
            'bandejas': {'codigo': '0080', 'itens': ['BAND SUSP SUP', 'BANDEJA', "BANDEJA DIANT", 'BANDEJA DIANTEIRA', 'BANDEJA INFERIOR', 'BANDEJA SUS', 'BANDEJA SUSPENSAO', 'SUPORTE BANDEJA DIANTEIRA']},
            'eixos_suspensao': {'codigo': '0132', 'itens': ['EIXO TRAS', 'PONTA EIXO ']},
            'kit_amortecedor': {'codigo': '0081', 'itens': ['BATENTE AMORT', 'BATENTE AMORTECEDOR', 'BATENTE BANDEJA', 'BATENTE BRACO', 'BATENTE DE MOLA', 'BATENTE DIANT', 'BATENTE EIXO', 'BATENTE FEIXE MOLA', 'BATENTE INF', 'BATENTE INFERIOR', 'BATENTE MOLA', 'BATENTE SUP', 'BATENTE SUSP', 'BATENTE COIFA', 'BOLACHA SANTA FE', 'BORRACHA BARRA ESTA', 'BORRACHA HASTE VALVULA', 'BORRACHA LIGACAO BARRA EST', 'KIT AMORTECEDOR', 'KIT AMORT DIANT', 'KIT AMORTECEDOR DIANT', 'KIT AMORTECEDOR SUSP', 'KIT AMORTECEDOR TRAS', 'KIT BATENTE AMORT', 'KIT BATENTE AMORTECEDOR', 'KIT BATENTE/COIFA', 'KIT DO AMORTECEDOR']},
            'molas': {'codigo': '0115', 'itens': ['MOLA SUSPENSAO', 'FEIXE MOLA', 'MOLA DIANT', 'MOLA DIANTEIRA', 'MOLA SUSPENSAO DIANTEIRA', 'MOLA SUSPENSAO TRASEIRA', 'MOLA TRAS', 'MOLA TRASEIRA', 'PAR MOLA TRAS']},
            'pratos': {'codigo': '0104', 'itens': ['ASSENTO SUPERIOR MOLA', 'KIT PRATO AMORTECEDOR', 'KIT PRATO LOCALIZADOR BATENTE', 'PRATO AMORTECEDOR', 'PRATO COXIM AMORT', 'PRATO LOCALIZADOR BATENTE DIANT', 'PRATO MOLA DIANT', 'PRATO MOLA VAL', 'PRATO SUPERIOR AMORTECEDOR DIANT', 'PRATO SUPERIOR MOLA DIANT']},
            'barra_estabilizadora': {'codigo': '0095', 'itens': ['BARRA ESTABILIZADORA', 'SUPORTE BARRA ESTABILIZADORA']},
            'kit_barra_estabilizadora': {'codigo': '0096', 'itens': ['KIT BARRA ESTAB', 'KIT BARRA ESTABILIZADORA', 'KIT ESTABILIZADOR']},
            'cubos_roda': {'codigo': '0076', 'itens': ['CUBO RODA', 'CUBO RODA DIANTEIR', 'CUBO RODA TRASEIR']},
        }
    },
    'transmissao': {
        'codigo': '0036',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BALENCEIRO EMBREAGEM', 'BARRA DE LIGACAO', 'CAIXA SATELITE', 'CANO EMBREAGEM', 'CAPA ROLAMENTO CARDAN', 'CANO GUIA CABO EMB', 'GUIA ROLAMENTO EMBREAGEM', 'KIT ABRACADEIRA', 'KIT GARFO EMBREAGEM', 'KIT SEPARADOR MOLA', 'PARAFUSO CAMBIO', 'PARAFUSO HOMOCINETICA', 'PARAFUSO CONVERSOR TORQUE', 'PARAFUSO ENGRENAGEM COMANDO', 'PARAFUSO FIXACAO COROA', 'PARAFUSO PIVO GARFO EMBREAGEM', 'PORCA BORBOLETA', 'PORCA HOMOCINETICA', 'RABETA CAIXA']},
            'buchas_transmissao': {'codigo': '0101', 'itens': ['BUCHA CAMBIO', 'BUCHA OLEO', 'BUCHA GARFO EMBR', 'BUCHA ADAPTADOR COMANDO EMBREAG', 'BUCHA LATERAL CAMBIO', 'BUCHA REFIL SUPORTE CAMBIO AUTO', 'GUIA CABO ENGATE MARCHA', 'GUIA PEDAL EMBREAGEM', 'GUIA ROLAMENTO EMBREAGEM', 'EIXO PILOTO 16 DENTES', 'KIT BUCHA CAIXA', 'KIT BUCHA TENSOR']},
            'embreagens': {'codigo': '0082', 'itens': ['DISCO EMBREAGEM', 'EMBREAGEM', 'GARFO EMBREAGEM', 'GARFO SINCRONIZADOR RE', 'GARFO TULIPA', 'KIT EMBREAGEM', 'PLATO', 'PLATO EMBREAGEM']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM MARCHA', 'ENGRENAGEM PLANETARIA', 'ENGRENAGEM VELOCIMETRO', 'JOGO ENGRENAGEM DIFERENCIAL']},
            'coifas': {'codigo': '0128', 'itens': ['COIFA CAMBIO', 'COIFA GUARDA PO', 'COIFA HASTE SELETORA', 'COIFA HOMOCINETICA', 'COIFA LADO CAMBIO', 'COIFA LADO RODA', 'COIFA RODA', 'COIFA SETOR', 'KIT COIFA CAIXA', 'KIT COIFA CAMBIO']},
            'cilindros_embreagem': {'codigo': '0083', 'itens': ['CILINDRO EMBRAGEM', 'CILINDRO EMB', 'CILINDRO AUXILIAR EMB', 'CILINDRO ESCRAVO']},
            'cilindros_mestre_embreagem': {'codigo': '0117', 'itens': ['CILINDRO MESTRE EMBREAGEM', 'CILINDRO MESTRE EMB']},
            'atuadores_embreagem': {'codigo': '0084', 'itens': ['ATUADOR EMBREAGE']},
            'homocineticas': {'codigo': '0068', 'itens': ['HOMOCINETICA', 'HOMOCINETICA DESLIZANTE', 'HOMOCINETICA RODA', 'JUNTA HOMOCINETICA', 'KIT JUNTA HOMOCINETICA']},
            'kit_coifa_homocinetica': {'codigo': '0092', 'itens': ['KIT COIFA HOMOCINETICA', 'KIT COIFA REPARO HOMOCINETICA']},
            'trizetas': {'codigo': '0094', 'itens': ['TRIZETA', '']},
            'tulipas': {'codigo': '0152', 'itens': ['TULIPA']},
            'cruzeta': {'codigo': '0125', 'itens': ['CRUZETA']},
            'coxins': {'codigo': '0078', 'itens': ['COXIM CAMBIO', 'COXIM TRANSMISSAO', 'COXIM LADO CAMBIO', 'COXIM RETO CAMBIO', 'COXIM AMORTECEDOR CAMBIO', 'COXIM CARDAN', 'COXIM EXT EIXO']}
        }
    },
#Sessão Elétrica
    'alternadores': {
        'codigo': '0038',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ALTERNADOR', 'BOMBA VACUO', 'PARAFUSO ALTERNADOR', 'SUPORTE ESCOVA ALTERNADOR', 'TRIODO', 'TRIODO ALTERNADOR', 'TRIODO EXCITACAO ALTERNADOR']},
            'retificador_alternador': {'codigo': '0184', 'itens': ['CONJUNTO RETIFICADOR', 'DIODO PLACA EXITADORA', 'PLACA DIODO ALTERNADOR', 'PLACA RETIFICADORA', 'RETIFICADOR']},
            'escovas_eletricas': {'codigo': '0186', 'itens': ['ESCOVA', 'ESCOVA DINAMO', 'ESCOVA ALTERNADOR', 'ESCOVA ARRANQUE', 'JOGO ESCOVA MOTOR', 'PORTA ESCOVA']},
            'estatores': {'codigo': '0187', 'itens': ['ESTATOR']},
            'mancais': {'codigo': '0206', 'itens': ['MANCAL', 'MANCAL ALTERNADOR']},
            'rotores': {'codigo': '0216', 'itens': ['ROTOR', 'ROTOR DISTRIBUIDOR']},
        }
    },
    'audio_entretenimento': {
        'codigo': '0039',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'antenas': {'codigo': '0156', 'itens': ['ANTENA', 'ANTENA ESTAGIO', 'ANTENA INTERNA', 'ANTENA TETO']},
            'caixas_som': {'codigo': '0157', 'itens': []},
            'radios': {'codigo': '0158', 'itens': ['CONVERSOR RCA']},
        }
    },
    'automaticos': {
        'codigo': '0040',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['AUTOMATICO', 'AUTOMATICO PARTIDA', 'BENDIX']},
        }
    },
    'buzinas': {
        'codigo': '0053',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BUZINA', 'SIRENE ELETRONICA']},
        }
    },
    'fiacao': {
        'codigo': '0041',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CABO (FIO) 16MM PARA POSITIVO', 'CABO BATERIA', 'CABO CONTROLE AR PAINEL', 'CABO NEGATIVO', 'CABO PARALELO SOM', 'CABO PONTE BATERIA', 'CABO RCA 5 METROS', 'CABO/CHUPETA', 'CAPA TERMINAL FIO FEMEA', 'EMENDA FIO', 'FIO INSTAL', 'ILHO PASSAGEM FIACAO', 'PASSA FIO', 'PORCA FIACAO']},
        }
    },
    'iluminacao': {
        'codigo': '0042',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ADAPTADOR LAMPADA H5 PARA H1', 'ADAPTADOR LAMPADA']},
            'circuitos_lanterna': {'codigo': '0180', 'itens': ['CIRCUITO LANTERNA', 'CIRCUITO SOQUETE LANTERNA', 'PAR CIRCUITO LANTERNA']},
            'lampadas_halogenas': {'codigo': '0200', 'itens': ['KIT LAMPADA H4', 'LAMPADA ASSIMETRICA', 'LAMPADA H5', 'LAMPADA H1', 'LAMPADA H11', 'LAMAPADA H13', 'LAMPADA H16', 'LAMPADA H27', 'LAMPADA H3', 'LAMPADA H4', 'LAMPADA H7', 'LAMPADA H8', 'LAMPADA HB1', 'LAMPADA HB3', 'LAMPADA HB4', 'LAMPADA HIR2']},
            'lampadas_halogenas_pequenas': {'codigo': '0201', 'itens': ['LAMPADA 1 POLO', 'LAMPADA 2 POLO', 'LAMPADA 69', 'LAMPADA BASE VIDRO', 'LAMPADA T67', 'LAMPADA T5', 'LAMPADA MINI', 'LAMPADA PAINEL', 'LAMPADA PINGAO', 'LAMPADA PINGO', 'LAMPADA TORPEDO', 'LAMPADA PISCA AMARELO', 'LAMPADA T315']},
            'lampadas_leds': {'codigo': '0202', 'itens': ['KIT LAMPADA H4 LED', 'LAMPADA H5 LED', 'LAMPADA H1 LED', 'LAMPADA H11 LED', 'LAMAPADA H13 LED', 'LAMPADA H16 LED', 'LAMPADA H27 LED', 'LAMPADA H3 LED', 'LAMPADA H4 LED', 'LAMPADA H7 LED', 'LAMPADA H8 LED', 'LAMPADA HB1 LED', 'LAMPADA HB3 LED', 'LAMPADA HB4 LED', 'LAMPADA HIR2 LED']},
            'lampadas_leds_pequenas': {'codigo': '0203', 'itens': ['KIT LAMPADA LED PINGO', 'LAMPADA 1 E 2 POLO LED', 'LAMPADA 1 LED', 'LAMPADA 1 POLO LED', 'LAMPADA 13 LEDS', 'LAMPADA 2 LEDS', 'LAMPADA 2 POLO LED', 'LAMPADA LED SILICONE', 'LAMPADA LED', 'LAMPADA LEDS', 'LAMPADA ESMAGADA LED', 'LAMPADA PAINEL LED', 'LAMPADA PINGAO LED', 'LAMPADA PINGO LED', 'LAMPADA TORPEDO LED']},
            'soquetes': {'codigo': '0217', 'itens': ['SOQUETE', 'SOQUETE CIRCUITO', 'SOQUETE FAROL', 'SOQUETE LAMPADA 2 POLOS', 'SOQUETE GLOBO', 'SOQUETE LAMPADA', 'SOQUETE LAMPADA PINGO', 'SOQUETE LANTERNA', 'SOQUETE LANTERNA DIANTEIRA', 'SOQUETE LISO', 'SOQUETE MEIA LUZ', 'SOQUETE METAL', 'SOQUETE MIRIM', 'SOQUETE PAINEL', 'SOQUETE PINGO', 'SOQUETE PISCA', 'SOQUETE UNIVERSAL']},
        }
    },
    'injecao': {
        'codigo': '0043',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['FILTRO BICO', 'FILTRO BICO INJETOR', 'FILTRO BICO ANEIS', 'FLAUTA INJE', 'KIT FLAUTA INJECAO']},
            'bicos_injetores': {'codigo': '0165', 'itens': ['BICO INJETOR', 'KIT BICO INJETOR']},
        }
    },
    'interruptores_sensores': {
        'codigo': '0044',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['SUPORTE SENSOR']},
            'interruptores': {'codigo': '0198', 'itens': ['INTERRUPTOR DE EMBREAGEM', 'INTERRUPTOR DE FREIO', 'INTERRUPTOR DIRECAO HIDRAULICA', 'INTERRUPTOR PRESSAO OLEO', 'INTERRUPTOR LUZ FREIO', 'INTERRUPTOR LUZ RE', 'INTERRUPTOR OLEO', 'INTERRUPTOR PARTIDA FRIO', 'INTERRUPTOR PEDAL', 'INTERRUPTOR RADIADOR', 'INTERRUPTOR RE', 'INTERRUPTOR REDUZIDA', 'INTERRUPTOR REGULAGEM', 'INTERRUPTOR RELE', 'INTERRUPTOR TEMPERATURA', 'INTERRUPTOR VENTILADOR', 'INTERRUPTOR LUZ', 'INTERRUPTOR DUPLO LUZ','INTERRUPTOR MOTOR']},
            'sensores': {'codigo': '0199', 'itens': ['INTERRUPTOR SENSOR', 'MEDIDOR FLUXO AR', 'MEDIDOR MASSA AR', 'SENSOR FLUXO AR', 'SENSOR ABS', 'SENSOR', 'SENSOR AR CONDICIONADO', 'SENSOR BOIA COMBUSTIVEL', 'SENSOR BORBOLETA', 'SENSOR NIVEL', 'SENSOR ROTACAO', 'SENSOR VELOCIDADE', 'SENSOR DESGASTE PASTILHA', 'SENSOR DETONACAO', 'SENSOR FASE', 'SENSOR FLUXO AR', 'SENSOR HALL', 'SENSOR MAP', 'SENSOR NIVEL', 'SENSOR PARTIDA', 'SENSOR PASTILHA', 'SENSOR POSICAO BORBOLETA', 'SENSOR POSICAO PEDAL', 'SENSOR PRESSAO', 'SENSOR ROTACAO', 'SENSOR TEMPERATURA', 'SENSOR VELOCIDADE', 'SONDA LAMBDA']},
        }
    },
    'reles': {
        'codigo': '0045',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ESTABILIZADOR PAINEL', 'ESTABILIZADOR VOLTAGEM', 'MINI RELE', 'PRESSOSTATO', 'RELE LAMPADA FLUORESCENTE', 'RELE', 'RELE AUXILIAR', 'RELE BUZINA', 'RELE VIDRO ELETRICO', 'RELE AVISO', 'RELE AR CONDICIONADO', 'RELE BOMBA', 'RELE BOMBA COMBUSTIVEL', 'RELE BOMBA INJECAO', 'RELE BUZINA UNIVERSAL', 'RELE COMANDO INJECAO ELETRONICA', 'RELE COMANDO PISCA', 'RELE DE INJECAO', 'RELE DESEMBACADOR', 'RELE DUPLO AUXILIAR', 'RELE DUPLO INJECAO', 'RELE ELETRONICO', 'RELE FAROL', 'RELE INJECAO', 'RELE ENGATE', 'RELE LIMPADOR', 'RELE MONITOR', 'RELE PARTIDA FRIO', 'RELE PISCA', 'RELE TEMPERATURA', 'RELE TEMPORIZADOR', 'RELE TEMPORIZADOR LIMPADOR', 'RELE UNIVERSAL', 'RELE VENTILADOR RADIADOR', 'RELE VENTOINHA RADIADOR', 'RELE VIDRO ELETRICO']},
        }
    },
    'botoes': {
        'codigo': '0047',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BOTAO CIGARRO', 'BOTAO BUZINA', 'BOTAO DESLIZANTE', 'BOTAO ESGUICHO/LIMPADOR', 'BOTAO VENTILADOR', 'BOTAO VENTILACAO', 'COMANDO VENTILACAO', 'INTERRUPTOR PORTA MALA', 'INTERRUPTOR AR COMPRIMIDO', 'INTERRUPTOR CAPO', 'INTERRUPTOR ESPELHO ELETRICO', 'INTERRUPTOR PAINEL', 'INTERRUPTOR PORTA', 'INTERRUPTOR RECIRCULACAO AR', 'INTERRUPTOR REGULAGEM ESPELHO', 'INTERRUPTOR TIC TAC', 'INTERRUPTOR TRAVA ELET', 'INTERRUPTOR UNIVERSAL BOTAO', 'KIT BOTAO BUZINA']},
            'botao_ar_condicionado': {'codigo': '0169', 'itens': ['BOTAO AR CONDICIONADO', 'BOTAO AR', 'BOTAO COMANDO AR COND', 'INTERRUPTOR AR CONDICIONADO']},
            'botao_ar_quente': {'codigo': '0170', 'itens': ['BOTAO AR QUENTE', 'BOTAO PAINEL AR QUENTE', 'INTERRUPTOR AR', 'INTERRUPTOR BOTAO AR', 'INTERRUPTOR DESEMBACADOR']},
            'botao_vidro_eletrico': {'codigo': '0171', 'itens': ['BOTAO VIDRO ELETRICO', 'BOTAO BLOQUEIO VIDRO', 'CAPA INTERRUPTOR VIDRO', 'INTERRUPTOR VIDRO', 'INTERRUPTOR BLOQUEIO VIDRO', 'INTERRUPTOR SIMPLES VIDRO', 'INTERRUPTOR VIDRO', 'INTERRUPTOR VIDRO ELET', 'INTERRUPTOR VIDRO ELETRICO']},
            'botao_iluminacao': {'codigo': '0172', 'itens': ['BOTAO FAROL', 'BOTAO FAROLETE', 'BOTAO CHAVE LUZ', 'INTERRUPTOR FAROL', 'INTERRUPTOR FAROLETE', 'INTERRUPTOR LUZ EMERGENCIA', 'INTERRUPTOR LUZ FAROL', 'INTERRUPTOR LUZ FAROLETE', 'INTERRUPTOR EMERGENCIA', 'INTERRUPTOR LUZ PAINEL']},
            'botao_ignicao': {'codigo': '0173', 'itens': ['BOTAO PARTIDA']}

        }
    },
    'ignicao': {
        'codigo': '0048',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BUCHA ACABAMENTO CABO VELA', 'BUCHA PARTIDA FRIO', 'CARVAO TAMPA DISTRI', 'CHAVE IGNICAO', 'CHAVE VIRGEM', 'CONTRA CAPA CHAVE ALARME', 'IMPULSOR PARTIDA', 'KIT TUCHO VELA', 'PARAFUSO REGULAGEM PARTIDA', 'PULA MACACO VELA', 'BOBINA IMPULSIONADORA']},
            'cabos_vela': {'codigo': '0159', 'itens': ['CABO DE VELA', 'CABO VELA', 'JOGO CABO VELA']},
            'velas': {'codigo': '0160', 'itens': ['JOGO VELA CIVIC', 'VELA', 'VELA AQUECEDORA', 'VELA IGNICAO']},
            'bobinas': {'codigo': '0161', 'itens': ['BOBINA CAMPO', 'BOBINA IGNICAO']},
            'distribuidores': {'codigo': '0162', 'itens': ['DISTRIBUIDOR', 'DISTRIBUIDOR BICO']},
            'cilindro_ignicao': {'codigo': '0179', 'itens': ['CILINDRO IGNICAO']},
            'comutador_ignicao': {'codigo': '0181', 'itens': ['COMANDO IGNICAO', 'COMUTADOR IGNICAO']},
            'induzidos': {'codigo': '0197', 'itens': ['INDUZIDO', 'INDUZIDO PARTIDA']},
        }
    },
    'modulos': {
        'codigo': '0049',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['MODULO AIR BAG', 'PARAFUSO ANTI FURTO', 'PORCA FIXACAO MODULO', 'MODULO ENGATE REBOQUE']},
            'modulo_alarme': {'codigo': '0163', 'itens': ['ANTENA/MODULO ALARME', 'MODULO CONTRA ROUBO', 'SISTEMA ANTI FURTO']},
            'modulo_travamento': {'codigo': '0176', 'itens': ['CENTRAL TRAVA ELETRICA', 'CENTRAL ELETRONICA TRAVA', 'CENTRALINA TECH LINE', 'KIT TRAVA ELETRICA', 'MODULO TRAVA ELETRICA', 'MODULO TRAVA ELETRONICA']},
            'modulo_vidro_eletrico': {'codigo': '0175', 'itens': ['CENTRAL VIDRO ELETRICO', 'INTERFACE COMANDO FECHAMENTO VIDRO', 'MODULO VIDRO ELETRICO', 'SISTEMA VIDRO ELETRICO', 'TEMPORIZADOR VIDRO ELETRICO']},
            'modulo_ignicao': {'codigo': '0207', 'itens': ['MODULO ELETRONICO', 'MODULO IGNICAO', 'MODULO INJECAO']},
        }
    },
    'fusiveis': {
        'codigo': '0050',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CAIXA DE FUSIVEL', 'CAIXA FUSIVEL', 'SUPORTE CAIXA FUSIV', 'PORTA FUSIVEL']},
            'fusivel_lamina': {'codigo': '0188', 'itens': ['FUSIVEL LAMINA']},
            'fusivel_lamina_grande': {'codigo': '0189', 'itens': ['FUSIVEL LAMINA MAXI GRANDE']},
            'fusivel_lamina_micro': {'codigo': '0190', 'itens': ['FUSIVEL LAMINA MICRO']},
            'fusivel_lamina_mini': {'codigo': '0191', 'itens': ['FUSIVEL LAMINA MINI']},
            'fusivel_mega': {'codigo': '0192', 'itens': ['FUSIVEL MEGA']},
            'fusivel_louca': {'codigo': '0193', 'itens': ['FUSIVEL LOUCA']},
            'fusivel_midi': {'codigo': '0194', 'itens': ['FUSIVEL MIDI']},
            'fusivel_reversor': {'codigo': '0195', 'itens': ['FUSIVEL REVERSOR']},
            'fusivel_vidro': {'codigo': '0196', 'itens': ['FUSIVEL VIDRO']},
        }
    },
    'motores_eletricos': {
        'codigo': '0051',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ARRASTE MAQ VIDRO', 'ARRASTE MAQUINA DE VIDRO', 'KIT VIDRO ELETRICO', 'PARAFUSO MOTOR PAR']},
            'motor_maquina_vidro': {'codigo': '0164', 'itens': []},
            'motor_parabrisa': {'codigo': '0208', 'itens': ['MOTOR LIMPADOR PARABRISA']},
            'motor_partida': {'codigo': '0209', 'itens': ['MOTOR PARTIDA']},
            'motor_passo': {'codigo': '0210', 'itens': ['MOTOR PASSO']},
            'motor_trava_eletrica': {'codigo': '0211', 'itens': ['MOTOR TRAVA ELETRICA']},
            'motor_ventilacao': {'codigo': '0212', 'itens': ['MOTOR VENTILADOR', 'MOTOR VENTOINHA']},
        }
    },
    'boias_eletricas': {
        'codigo': '0052',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'boia_combustivel': {'codigo': '0098', 'itens': ['BOIA COMBUSTIVEL',"BOIA TANQUE", 'BOIA TANQUE', 'REFIL BOMBA COMB']},
        }
    },
    'bombas_eletricas': {
        'codigo': '0053',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'bomba_combustivel': {'codigo': '0166', 'itens': ['BOMBA COMBUSTIVEL', 'BOMBA IGNICAO', 'BOMBA INJECAO COMB', 'BOMBA INJECAO COMBUSTIVEL', 'CONJUNTO BOMBA COMBUSTIVEL']},
            'bomba_esguicho': {'codigo': '0167', 'itens': ['BOMBA AGUA PARABRISA', 'BOMBA ESGUICHO', 'BOMBA LAVA PARABRISA', 'BOMBA LIMPADOR PARABRISA', 'BOMBA RESERVATORIO LIMPADOR']},
        }
    },
    'chaves_seta': {
        'codigo': '0054',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CAPA CHAVE SETA', 'CHAVE LIMPADOR', 'CHAVE SETA']},
            'cames': {'codigo': '0174', 'itens': ['CAME', 'CAME BUZINA', 'CAME RETORNO', 'CAME VOLANTE', 'PLATINADO']},
        }
    },
    'chicotes_conectores': {
        'codigo': '0055',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'conector_sem_chicote': {'codigo': '0177', 'itens': ['CONECTOR', 'CONECTOR VIA', 'CONECTOR VIAS', 'CONECTOR INJECAO', 'CONECTOR SENSOR', 'CONEXAO PARTIDA', 'CORDOALHA', 'GARRA BATERIA', 'PAR GARRAS BATERIA', 'TERMINAL BATERIA', 'TERMINAL FEMEA', 'TERMINAL FIO', 'TERMINAL FORQUILHA', 'TERMINAL MACHO', 'TERMINAL OLHAL']},
            'conector_com_chicote': {'codigo': '0178', 'itens': ['CHICOTE', 'CHICOTE CONECTOR BOTAO', 'CHICOTE VIA', 'CHICOTE VIAS', 'CHICOTE ALTERNADOR', 'CHICOTE BOBINA', 'CHICOTE BICO', 'CHICOTE BOMBA COMBUS', 'CHICOTE CARCACA', 'CHICOTE FAROL', 'CHICOTE FAROLETE', 'CHICOTE FIACAO', 'CHICOTE IGNICAO', 'CHICOTE INJECAO ELETRONICA', 'CHICOTE INTERRUPTOR', 'CHICOTE LAMPADA', 'CHICOTE MOTOR', 'CHICOTE PAINEL', 'CHICOTE REGULADOR', 'CHICOTE RELE 4 VIAS', 'CHICOTE REPARO', 'CHICOTE REPARO BICO', 'CHICOTE REPARO INFERIOR', 'CHICOTE REPARO INFERIOR', 'CHICOTE REPARO VIDRO', 'CHICOTE SENSOR', 'CHICOTE SONDA', 'CHICOTE SONDA LAMBDA', 'CHICOTE UNID COMANDO', 'CHICOTE UNIVERSAL', 'CHICOTE VIDRO ELETRICA']},

        }
    },
    'ventilacao_eletrica': {
        'codigo': '0056',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'condensadores': {'codigo': '0182', 'itens': ['CONDENSADOR']},
            'eletroventiladores': {'codigo': '0183', 'itens': ['ELETROVENTILADOR', 'VENTILADOR CONDENSADOR']},
            'eletrobombas': {'codigo': '0185', 'itens': ['ELETROBOMBA', 'ELETROBOMBA BICO']},
            
        }
    },
    'marcadores': {
        'codigo': '0057',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['INDICADOR COMB', 'INDICADOR DE PAINEL']},
        }
    },
    'travas_eletricas': {
        'codigo': '0058',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['KIT TRAVA ELETRICA', 'TRAVA ELETRICA', 'TRAVA DIRECAO']},
            'suporte_trava_eletrica': {'codigo': '0204', 'itens': ['KIT SUPORTE TRAVA ELETRICA']},
        }
    },
    'reguladores': {
        'codigo': '0059',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': []},
            'reguladores_pressao': {'codigo': '0213', 'itens': ['REGULADOR PRESSAO']},
            'reguladores_voltagem': {'codigo': '0214', 'itens': ['REGULADOR VOLTAGEM', 'REGULADOR TENSAO']},
            'reguladores_velocidade': {'codigo': '0215', 'itens': ['REGULADOR VELOCIDADE']},
        }
    },
    'resistores': {
        'codigo': '0060',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['RESISTOR', 'RESISTENCIA', 'RESISTENCIA AR', 'RESISTENCIA ELETROVENTILADOR', 'RESISTENCIA VENTOINHA']},
        }
    },
}





# Função para verificar o código do grupo e subgrupo de um item
def verificar_item(item):
    maior_item_subgrupo = ""
    for grupo, dados_grupo in grupos.items():
        for subgrupo, info_subgrupo in dados_grupo['subgrupos'].items():
            for item_subgrupo in info_subgrupo['itens']:
                termos_subgrupo = item_subgrupo.split()
                if all(termo in item for termo in termos_subgrupo) and len(item_subgrupo) > len(maior_item_subgrupo):
                    maior_item_subgrupo = item_subgrupo

    if maior_item_subgrupo:
        for grupo, dados_grupo in grupos.items():
            for subgrupo, info_subgrupo in dados_grupo['subgrupos'].items():
                if maior_item_subgrupo in info_subgrupo['itens']:
                    return dados_grupo['codigo'], info_subgrupo['codigo']

    return None, None  # Retorna None se nenhum subgrupo for encontrado no item

def corrigir_descricao(item): # Função de situação específica, o objetivo era acrescentar à descrição a informação de silencioso
        if "ESCAPAMENTO" and "TRAS" not in item:
            exit()
        pyautogui.click(x=374, y=623)
        time.sleep(0.5)
        pyautogui.press("space")
        time.sleep(0.5)
        pyautogui.typewrite("SILENCIOSO")
        time.sleep(0.5)

print("---------------------------------------------------------------------------------------")
print("Bem-vindo ao SectionDescripted, o programa que classifica grupos e subgrupos com base nas descrições de itens.") # Mensagem de boas vindas
option = "" # Variável que receberá a opção selecionada
while option != "2":
    print("Para começar, analise a opção desejada: \n 1 - Iniciar classificação \n 2 - Sair do programa") # Mensagem de seleção de opções
    option = input("Digite o número da opção desejada: ") 
    if option == "1":
        print("_____________________________________________________________________________")
        print("Iniciando operação de classificação de itens em 5 segundos...") 
        time.sleep(1) #
        print("4 segundos...")
        time.sleep(1)
        print("3 segundos...")
        time.sleep(1)
        print("2 segundos...")
        time.sleep(1)
        print("1 segundo...")
        time.sleep(1)
        print("Iniciando operação...") 
        tempo_inicial = time.time() # Regra para definir o período de tempo
        contadorverificados = -1 
        while(time.time() - tempo_inicial) < tempo_de_execucao: # Loop de execução enquanto o contador de tempo estiver ativo
            subgrupoconfirm = False # Define a seleção de código para subgrupo como indefinida até a possível necessidade
            contadorverificados += 1
            print(f"_______________________________")
            print(f"Número de verificações: {contadorverificados}") 
            screenshotwatcher = pyautogui.screenshot(region=(0, 24, 150, 20)) # Primeira variável de segurança, captura a tela no tamanho e posição definidos (x, y, largura e altura)
            screenshotwatcher = screenshotwatcher.convert("L") # Converte a captura para escala monocromática, permitindo uma melhor conversão de dados
            screenshotwatcher.save('screenshotwatcher.png') 
            from PIL import Image # Importa a biblioteca PIL para interpretação de imagens
            screenshotwatcher = Image.open('screenshotwatcher.png')
            textwatcher = pytesseract.image_to_string(screenshotwatcher) # Cria uma variável que recebe dados strings transformados pelo pytesseract, o qual interpreta a imagem e localiza textos.
            watch = 'Livre' 
            watch2 = 'campos' 
            time.sleep(0.8) 
            print(textwatcher)

            if watch in textwatcher or watch2 in textwatcher: 
                time.sleep(0.2)              
                screenshotdesc = pyautogui.screenshot(region=(280, 614, 458, 15)) # Captura a descrição do item
                screenshotdesc = screenshotdesc.convert("L")
                screenshotdesc.save('screenshotdesc.png')
                from PIL import Image
                screenshotdesc = Image.open('screenshotdesc.png')
                textdesc = pytesseract.image_to_string(screenshotdesc) 
                print(textdesc)
                grupoescolhido, subgrupo_escolhido = verificar_item(textdesc)

                # if "ESCAPAMENTO" and "TRAS" or "ESCAPAMENTO" and "TRASEIRO" in textdesc: # Complemento de situação específica
                #     corrigir_descricao(textdesc)
                #     time.sleep(0.5)
                #     pyautogui.doubleClick(x=1124, y=622)
                #     time.sleep(0.2)

                if grupoescolhido:
                    pyautogui.typewrite(grupoescolhido)
                    if subgrupo_escolhido:
                        time.sleep(0.2) 
                        pyautogui.press("tab")
                        time.sleep(0.1)
                        pyautogui.typewrite(subgrupo_escolhido)
                        subgrupoconfirm = True
                                
                time.sleep(0.2) 
                pyautogui.press("down")
                # time.sleep(0.2) # Caso haja necessidade de correção de itens do sistema quanto as suas descrições
                # pyautogui.press("down")
                # time.sleep(0.2)
                # pyautogui.click(x=1344, y=79)
                if subgrupoconfirm == True: # Uso do booleano para quando o subgrupo for alterado
                    time.sleep(0.2)
                    pyautogui.press("left")
                time.sleep(0.1)
            else:
                exit()
    elif option == "2": # Se a opção for 4, sai do programa
        print("Saindo do programa...")
        break