import requests
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("API_KEY")
api_token = os.getenv("API_TOKEN")

board_id = '65fa58235477f5d74517cfcb'
list_id = '6705965cf7120cbb53bb28e3'

# Seu dicionário de grupos e subgrupos
dicionario = {
    'ar_condicionado': {
        'codigo': '0037',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CONJUNTO EMBREAGEM COMPRESSOR', 'MAGNETICO COMPRESSOR', 'COMPRESSOR AR CONDICIONADO', 'KIT ACESSORIOS COMPRESSOR AR']},
        }
    },
    'arrefecimento': {
        'codigo': '0020',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BRUCUTU', 'BUCHA BOMBA ESGUICHO', 'KIT CAVALETE DISTR AGUA', 'PRESILHA FIX SUPORTE RADIADOR', 'SUPORTE COXIM RADIADOR']},
            'buchas_arrefecimento': {'codigo': '0113', 'itens': ['BUCHA RADIADOR', 'BUCHA BOMBA ESGUICHO', 'BUCHA RESERVATORIO GAS PARTIDA']},
            'radiadores': {'codigo': '0008', 'itens': ['INTERCOOLER', 'RADIADOR', 'RADIADOR AGUA']},
            'bombas_agua': {'codigo': '0009', 'itens': ['BOMBA AGUA', 'BOMBA D.HIDR', 'BOMBA DAGUA']},
        }
    },
    'cabos': {
        'codigo': '0021',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CABO ACIONADOR PORTINHOLA', 'CABO AR FORCADO', 'CABO PORTA CORRER', 'CABO PORTA MALA', 'CABO PORTINHOLA', 'CABO TEMPERATURA', 'PARAFUSO QUEBRA GALHO CABO ACELERADOR', 'SUPORTE CABO EMBREAGEM', 'SUPORTE CABO', 'TAMPA PORTINHOLA']},
            'cabos_acelerador': {'codigo': '0011', 'itens': ['CABO ACEL', 'CABO ACELERADO', 'CABO DE ACELERADOR', 'CABO PARADA MOTOR']},
            'cabos_embreagem': {'codigo': '0012', 'itens': ['CABO EMB', 'CABO EMBR', 'CABO EMBREAGEM', 'CABO FLEX EMBR', 'CABO TRANSMISSAO', 'FLEXIVEL EMBREAGEM']},
            'cabos_freio': {'codigo': '0013', 'itens': ['CABO DE FREIO', 'CABO FREIO', 'CABO LIBERACAO FREIO']},
            'cabos_capo': {'codigo': '0014', 'itens': ['CABO CAPO', 'CABO PUXADOR CAPO', 'CABO ABERTURA CAPO']},
            'cabos_velocimetro': {'codigo': '0015', 'itens': ['CABO DE VELOCIMETRO', 'CABO TACOGRAFO', 'CABO TACOMETRO', 'CABO VELOCIMETRO', 'CABO VELOC']},
            'cabos_tampa_traseira': {'codigo': '0016', 'itens': ['CABO LIMITADOR DA TAMPA TRAS', 'CABO PUXADOR TAMPA', 'CABO TAMPA TRAS', 'CABO LIMITADOR TAMPA']},
            'cabos_afogador': {'codigo': '0017', 'itens': ['CABO AFOGADOR', 'CABO ESTRANGULADOR']},
            'cabos_cambio': {'codigo': '0018', 'itens': ['CABO CAMBIO', 'CABO COMANDO', 'CABO COMANDO MARCHA', 'CABO ENGATE COMANDO', 'CABO ENGATE', 'CABO ENGATE MARCHA', 'CABO MARCHA', 'CABO REDUZIDA', 'CABO SELECAO CAMBIO', 'CABO SELECAO MARCHA', 'CABO SELECAO COMANDO']},
            'cabos_fechadura': {'codigo': '0019', 'itens': ['CABO COMANDO FECHADURA', 'CABO FECHADURA', 'HASTE CABO FECHADURA', 'HASTE FECHADURA']},
            'cabos_macaneta': {'codigo': '0232', 'itens': ['CABO ACION MACANETA', 'CABO ACO LIGACAO MACANETA', 'CABO DESTRAVA PORTA', 'CABO MACANETA']},
            'cabos_maquina_vidro': {'codigo': '0256', 'itens': ['CABO MAQUINA VIDRO']},
            'cabos_trava_banco': {'codigo': '0233', 'itens': ['CABO TRAVA BANCO']},
            'terminais_cabo': {'codigo': '0151', 'itens': ['TERMINAL CABO COMANDO', 'TERMINAL CABO ENGATE', 'TERMINAL CABO MARCHA', 'TERMINAL CABO SELECAO', 'TERMINAL CABO NEG']},
        }
    },
    'carburacao': {
        'codigo': '0022',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['AVANCO DISTRIBUIDOR', 'BOIA CARBURADOR', 'AFOGADOR', 'AVANCO DO DISTRIBUIDOR',   'CONJUNTO VALVULA BOIA CARBURADOR', 'EIXO CARBURADOR', 'KIT POSICIONADOR AFOGADOR', 'PARAFUSO MISTURADOR REGULAGEM', 'PORTA GICLE MARCHA CARBURADOR', "SAPATILHA CAME DEFOGADOR CARBURADOR"]},
            'carburadores': {'codigo': '0021', 'itens': ['CARBURADOR', 'KIT CARBURADOR']},
            'componentes_carburadores': {'codigo': '0022', 'itens': ["AGULHA CARBURADOR", 'BASE CARB', 'BASE CARBURADOR', 'BASE VEDACAO CARB', 'BENGALA CARB', 'BENGALA INJETOR CARBURAD', 'BENGALA SAIDA TANQUE', 'BORBOLETA CARBURADOR', 'ESGUICHO CARB', 'GICLE CARBURADOR', 'HASTE CARBURADOR', 'ESGUICHO CARBURADOR', 'ESPACADOR BASE CARB',  'FILTRO DIFUSOR SECUNDARIO', 'PISTAO ANEL MOTOR', 'PISTAO REPARO PINCA', 'PISTAO CARBURADOR']},
            'diafragmas_carburadores': {'codigo': '0122', 'itens': ['DIAFRAGMA CARBURADO', 'DIAFRAGMA ACELERA']},
        }
    },
    'carcacas_tubos': {
        'codigo': '0035',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['PORCA FLANGE COMB', 'PROTETOR CALOR CAIXA AR', 'VENTURI CARBURADOR', 'PARAFUSO OCO TUBO']},
            'antichama': {'codigo': '0105', 'itens': ['ANTICHAMA', 'ANTI CHAMA', 'DEFLETOR ANTICHAMA']},
            'cavaletes': {'codigo': '0106', 'itens': ['CAVALETE', 'FLANGE CAVALETE AGUA']},
            'tubos': {'codigo': '0107', 'itens': ['TUBO ABASTECIMENTO', 'TUBO RESPIRO', 'TUBO AGUA', 'TUBO AR PAINEL', 'TUBO CILINDRO', 'TUBO CIRCULACAO AGUA', 'TUBO COLETOR', 'TUBO CIRCULACAO', 'TUBO COLETOR', 'TUBO COMBUSTIVEL', 'TUBO CONEXAO', 'TUBO DIRECAO HIDRAULICA', 'TUBO DISTRIBUIDOR', 'TUBO DE FREIO', 'TUBO FLANGE', 'TUBO FLUXO AGUA', 'TUBO GARGALO', 'TUBO LIGACAO', 'TUBO MANGUEIRA', 'TUBO MISTURADOR CARBURADOR', 'TUBO MOTOR', 'TUBO RADIADOR', 'TUBO REFRIGERACAO', 'TUBO RETORNO', 'TUBO SAIDA COMBUSTIVEL', 'TUBO SUPERIOR', 'TUBO VENTILACAO', 'TUBO CONEXAO BOMBA', 'TUBO CANO EMBREAGEM', 'TUBO CORRUGADO BOMBA', 'TUBO MANGUEIRA DIRECAO', 'TUBO LUBRIFICACAO','TUBO MANGUEIRA TANQUE']},
            'conectores': {'codigo': '0108', 'itens': ['CONECTOR LIGACAO MANGUEIRA', 'CONECTOR MANGUEIRA', 'CONECTOR 3/8', 'CONECTOR AGUA', 'CONECTOR CAMB', 'CONECTOR DUPLO UNIVE', 'CONECTOR GASOLINA', 'CONECTOR QUICK', 'CONECTOR SELADO', 'CONECTOR UNIVERSAL', 'CONEXAO 1/8X27', 'CONEXAO COLETOR ADMISSAO', 'CONEXAO HIDROVACUO', 'CONEXAO RESERVATORIO', 'CONEXAO AGUA', 'CONEXAO CARC VALV', 'CONEXAO COM REGISTRO', 'CONEXAO DUPLA MANG', 'CONEXAO ESGUICHO', 'CONEXAO INF', 'CONEXAO MANG', 'CONEXAO RAPIDA', 'CONEXAO RADIADOR', 'CONEXAO SAIDA AR', 'CONEXAO T DUPLA', 'CONEXAO T TUBULACAO', 'CONEXAO Y DUPLO', 'EMENDA CONEXAO']},
            'cotovelos': {'codigo': '0109', 'itens': ['CONEXAO (COTOVELO)', 'COTOVELO', 'COTOVELO CAVALETE']},
            'capas_correias': {'codigo': '0110', 'itens': ['CAPA CORREIA', 'JOGO PROTETOR CORREIA', 'KIT CAPA PROTETOR CORREIA', 'KIT CAPA CORREIA', 'KIT PROTETOR CORREIA', 'PROTETOR CORREIA']},
            'carcacas': {'codigo': '0111', 'itens': ['CARCACA', 'CAIXA FILTRO AR', 'CAIXA FILTRO AR CARB', 'CAMARA VALVULA TERMOS']},
            'flanges': {'codigo': '0131', 'itens': ['FLANGE  MOTOR', 'FLANGE MANG CABECOTE', 'FLANGE AGUA', 'FLANGE BOMBA DAGUA', 'FLANGE CONEXAO', 'FLANGE ROLAMENTO CAIXA CAMBIO', 'FLANGE SEMI EIXO', 'FLANGE TERMOSTATO', 'FLAGE TUBO MANGUEIRA', 'FLANGE VALV TERMOST']},
            'kits_carcacas': {'codigo': '0112', 'itens': []},
        }
    },
    'combustivel': {
        'codigo': '0034',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ADAPTADOR TAMPA TANQUE", 'BORRACHA FLANGE COM', 'CANO COMBUSTIVEL', 'PORCA TAMPA BOMBA COMB']},
            'flanges_combustivel': {'codigo': '0089', 'itens': ["ADAPTADOR FLANGE CAIXA", "FLANGE", 'FLANGE COMBUSTIVEL', 'FLANGE MODULO COMBUSTIVEL']},
            'tanque_combustivel': {'codigo': '0151', 'itens': ['TANQUE COMBUSTIVEL', 'CILINDRO GNV']},
        }
    },
    'correias': {
        'codigo': '0023',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['CORREIA VENTOINHA', 'KIT CORREIA E TENSOR', 'PARAFUSO TENSOR CORREIA', 'CORRENTE COMANDO']},
            'correias_dentadas': {'codigo': '0023', 'itens': ['CORREIA COMANDO', 'CORREIA DENTADA', 'KIT CORREIA COM', 'KIT CORREIA COMANDO']},
            'correias_polyv': {'codigo': '0024', 'itens': ['CORREIA ALT', 'CORREIA ALTERNADOR', 'CORREIA AR COND', 'CORREIA MICRO V', 'CORREIA POLY V', 'CORREIA MULTI V', 'KIT CORREIA VIRABREQUIM']},
            'correias_em_v': {'codigo': '0119', 'itens': ['CORREIA EM V', 'CORREIA EM V AR COND', 'CORREIA EM V ALT']},
        }
    },
    'direcao': {
        'codigo': '0024',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ADAPTADOR VOLANTE", 'BORRACHA FIXADORA CAIXA DIRE', 'BORRACHA FIXACAO SETOR', 'PARAFUSO FIXO TUBO DIRECAO', 'PARAFUSO PORCA PIVO', 'PORCA CASTELO RODA', 'PORCA CUBO', 'PORCA RODA', 'PORCA ENCOSTO', 'PORCA PONTO EIXO', 'PORCA RODA', 'CHAVETA EIXO']},
            'buchas_direcao': {'codigo': '0102', 'itens': ["BUCHA COLUNA DIRECAO", 'BUCHA SETOR DIRECAO', 'BUCHA BRACO', 'BUCHA INF BRACO', 'BUCHA CAIXA DIRECAO', 'BUCHA COLUNA DIRECAO', 'BUCHA CAIXA DIRECAO', 'BUCHA FIX SETOR DIRECAO', 'BUCHA NUCLEO ARTIC', 'BUCHA TERMINAL DIRECAO']},
            'bombas_direcao': {'codigo': '0099', 'itens': ['BOMBA DIRECAO HIDRAULICA', 'BOMBA HIDRAULICA']},
            'caixas_direcao': {'codigo': '0025', 'itens': []},
            'coifas_direcao': {'codigo': '0128', 'itens': ['COIFA SETOR', 'KIT COIFA SETOR']},
            'setor_direcao': {'codigo': '0026', 'itens': ['SETOR DIRECAO', 'SETOR RECON']},
            'barras_axiais': {'codigo': '0027', 'itens': ['BARRA AXIAL', 'BARRA BRACO TENSOR', 'BARRA DIRECAO', 'BARRA LATERAL', 'BRACO AUXILIAR', 'BRACO DIANT INF', 'BRACO OSCILANT', 'BRACO PITMAN', 'BRACO SETOR', 'BRACO SUSP', 'BRACO TENSOR', 'SUPORTE BRACO TENSOR']},
            'pivos': {'codigo': '0067', 'itens': ['PIVO', 'PIVO INFERIOR', 'PIVO', 'PIVO SUSP', 'KIT PIVO SUSP']},
            'terminal_direcao': {'codigo': '0093', 'itens': ['TERMINAL DIR', 'TERMINAL DIRECAO', 'TERMINAL SUSPENSAO', 'TERMINAL BARRA DIRECAO']},
            'colunas_direcao': {'codigo': '0124', 'itens': ['COLUNA DIR', 'COLUNA DIRECAO', 'JUNCAO COLUNA DIRECAO']},
            'cubos_direcao': {'codigo': '0126', 'itens': ['CUBO DIRECAO', 'CUBO VOLANTE']},
        }
    },
    'filtros': {
        'codigo': '0025',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['FILTRO DAGUA', 'FILTRO HIDRAULICO']},
            'filtros_ar': {'codigo': '0028', 'itens': ['FILTRO AR', 'FILTRO CARBURADOR']},
            'filtros_combustivel': {'codigo': '0029', 'itens': ['FILTRO BOMB COMB', 'FILTRO COMBUSTIVEL', 'FILTRO DIESEL', 'FILTRO CANISTER', 'FILTRO SEDIMENTADOR', 'PRE FILTRO', 'PRE FILTRO BOMBA COMB', 'PRE FILTRO COMB']},
            'filtros_de_oleo': {'codigo': '0030', 'itens': ['FILTRO OLEO', 'FILTRO DE OLEO', 'FILTRO RETORNO']},
            'filtros_de_ar_condicionado': {'codigo': '0074', 'itens': ['FILTRO AR CONDICIONADO']},
            'filtros_de_cabine': {'codigo': '0075', 'itens': []},
            'filtros_cambio': {'codigo': '0130', 'itens': ['FILTRO CAIXA AUTOMATICA', 'FILTRO CAMB', 'FILTRO CAMBIO', ]}
        }
    },
    'freios': {
        'codigo': '0026',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ACIONADOR FREIO", "ACIONADOR/GATILHO FREIO", 'JUNCAO GUIA CABO FREIO', 'KIT FREIO', 'PARAFUSO SANGRADOR', 'PRATO FREIO' ]},
            'arrebite': {'codigo': '0227', 'itens': ['ARREBITE REBITE LONA FREIO']},
            'pastilhas_freio': {'codigo': '0031', 'itens': ['PASTILHA FREIO', 'PASTILHA FREIO DIANT', 'PASTILHA FREIO DIANTEIRO', 'PASTILHA FREIO TRASEIRO', 'PASTILHA FREIO TRAS', 'PASTILHA TRAS']},
            'coifas_freio': {'codigo': '0128', 'itens': ['COIFA FREIO']},
            'canos_freio': {'codigo': '0116', 'itens': ['CANO DE FREIO', 'CANO FREIO']},
            'discos_freio': {'codigo': '0032', 'itens': ['DISCO FREIO', 'DISCO FREIO DIANT', "DISCO FREIO TRAS"]},
            'tambores_freio': {'codigo': '0033', 'itens': ['TAMBOR FREIO', 'TAMBOR FREIO TRASEIRO', 'TAMBOR ']},
            'flexiveis_freio': {'codigo': '0034', 'itens': ['BIFURCACAO AO FLEXIVEL', 'FLEXIVEL', 'FLEXIVEL FREIO', 'FLEX DIANT', 'FLEXIVEL TRAS', 'FLEXIVEL FREIO DISCO', 'FLEXIVEL TRAS']},
            'pincas_freio': {'codigo': '0035', 'itens': ['PINCA FREIO']},
            'cilindros_roda_freio': {'codigo': '0036', 'itens': ['CILINDRO RODA']},
            'cilindros_mestre_freio': {'codigo': '0037', 'itens': ['CILINDRO MESTRE', 'CILINDRO MESTRE FREIO']},
            'lonas_freio': {'codigo': '0038', 'itens': ['LONA', 'LONA FREIO', 'LONA FREIO TRAS']},
            'sapatas_freio': {'codigo': '0039', 'itens': ['PATIM', 'PATIM SAPATA FREIO']},
            'servo_freios': {'codigo': '0087', 'itens': ["ACIONADOR FREIO", "ALAVANCA ACIONAMENTO FREIO", "GATILHO FREIO", 'SERVO FREIO', 'SERVO FREIO BENDIX', 'SERVO FREIO REMANUFATURADO']},
        }
    },    
    'juntas_retentores': {
        'codigo': '0027',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['JUNTA BOMBA COMBUS', 'JUNTA SENSOR TEMP', 'JUNTA BASE CARBURADOR', 'JUNTA CONEXAO SENSOR TEMPERATURA', 'JUNTA CONEXAO SENSOR TEMPERATURA', 'JUNTA CURTICA', 'JUNTA LUBRIFICACAO', 'JUNTA RADIADOR', 'JUNTA TAMPA BOMBA', 'JUNTA TAMPA ARVORE', 'JUNTA TAMPA DIFERENCIAL', 'JUNTA TAMPA OLEO', 'JUNTA TAMPA TRAS', 'JUNTA SUPERIOR FILTRO OLEO', 'JUNTA SUPORTE ROLAMENTO', 'JUNTA VELUMOIDE', 'KIT JUNTA RADIADOR', 'RETENTOR BOMBA HIDRAULICA', 'RETENTOR BOMBA INJETORA', 'RETENTOR SELO COMPRESSOR', 'VELUMOIDE JUNTAS']},
            'aneis': {'codigo': '0091', 'itens': ['ANEIS PISTAO', 'ANEL PISTAO', 'ANEL BUJAO', 'ANEL AJUSTE ROLAMENTO', 'ANEL ALAVANCA', 'ANEL ENCOSTO', 'ANEL AMORTECEDOR', 'ANEL ANTI RUIDO', 'ANEL BOCAL TANQUE', 'ANEL BORRACHA', 'ANEL BRACO SUSP', 'ANEL CARCACA', 'ANEL CEBOLAO', 'ANEL CILINDRO', 'ANEL COLETOR', 'ANEL VEDACAO', 'ANEL EIXO TRAS', 'ANEL IMPULSOR ARV', 'ANEL INFERIOR CARRO', 'ANEL INTERMEDIARIO', 'ANEL JUNTA', 'ANEL MALHA ACO', 'ANEL MOTOR', 'ANEL RADIADOR', 'ANEL RODA', 'ANEL SILENCIOSO', 'ANEL SINCRONIZ', 'ANEL TAMPA VALV', 'ANEL TIRANTE SUSP', 'ANEL TRASEIRO', 'ANEL TRAVA', 'ANEL VEDACAO', 'ANEL VEDADOR', 'ANEL JUNTA DISTRI', 'ANEL TOMADA FORCA', 'BORRACHA BOCAL', 'GARFO ANEL', 'ANEL ESCAPAMENTO', 'JOGO ANEL', 'JOGO ANEIS', 'JOGO ANEIS COLETOR ADMISSAO']},
            'diafragmas_tampa': {'codigo': '0127', 'itens': ['DIAFRAGMA TAMPA VALVU', 'DIAFRAGMA FREIO']},  
            'jogo_juntas': {'codigo': '0133', 'itens': ['JOGO JUNTA', 'JUNTA COMPLETA RETENTOR']},  
            'juntas_bombas_agua': {'codigo': '0143', 'itens': ['JUNTA BASE BOMBA AGUA', 'JUNTA BOMBA AGUA', 'JUNTA CONEXAO BOMBA AGUA']},  
            'juntas_cabecote': {'codigo': '0040', 'itens': ['JUNTA CABECOTE', 'JUNTA CABE', 'JUNTA FLANGE CABE', 'JUNTA INF CABEC']},
            'juntas_coletor': {'codigo': '0041', 'itens': ['JUNTA ADMISSAO', 'JUNTA COLETOR', 'JUNTA COL', 'JUNTA CONECTOR COLETOR ADM']},
            'juntas_cambio': {'codigo': '0134', 'itens': ['JUNTA CAMBIO', 'JUNTA CAIXA', 'JUNTA DIFERENCIAL', 'JUNTA EIXO DIANT', 'KIT MANCA CAIXA']},
            'juntas_carburador': {'codigo': '0135', 'itens': ['JUNTA CARBURADOR', 'KIT JUNTA CARB', 'KIT JUNTA CARBURADOR']},
            'juntas_carter': {'codigo': '0042', 'itens': ['JUNTA CARTER', 'JUNTA INFERIOR CART', 'KIT TAMPA CARTER']},
            'juntas_escapamento': {'codigo': '0136', 'itens': ['JUNTA CATALISADOR', 'JUNTA COLETOR ESC', 'JUNTA COLETOR ESCAPAMENTO', 'JUNTA ENTRADA COLETOR', 'JUNTA ESCAP', 'JUNTA ESCAPAMENTO', 'JUNTA ESCAPE', 'JUNTA SAIDA ESCAP', 'KIT JUNTA COLETOR ESCAP']},
            'juntas_injecao': {'codigo': '0137', 'itens': ['JUNTA INJ', 'JUNTA INJECAO', 'JUNTA TBI', 'KIT JUNTA INJECAO']},
            'juntas_motor': {'codigo': '0138', 'itens': ['JUNTA MOTOR', 'JUNTA RETIFI', 'JUNTA RETIFICA', 'JUNTA SUPERIOR MOTOR']},
            'juntas_tampa_valvula': {'codigo': '0043', 'itens': ['JUNTA TAMPA VALVULA', 'JUNTA INTERM TAMPA VALV', 'JUNTA RETENTOR ANEL TAMPA''JUNTA TAMP VALV', 'KIT JUNTA TAMPA VALV']},
            'juntas_tampa_distribuidor': {'codigo': '0044', 'itens': ['JUNTA TAMPA DIST']}, 
            'retentores_eixo': {'codigo': '0045', 'itens': ['RETENTOR CAIXA DIRECAO', 'RETENTOR CUBO RODA', 'RETENTOR EIXO', 'RETENTOR EXTERNO RODA', 'RETENTOR INTERNO RODA', 'RETENTOR PINO MESTRE', 'RETENTOR POLIA', 'RETENTOR RODA DIANT', 'RETENTOR RODA EIXO', 'RETENTOR RODA TRAS', 'RETENTOR SEMI EIXO', 'RETENTOR VOLANTE']},
            'retentores_virabrequim': {'codigo': '0046', 'itens': ['RETENTOR DIANT VIRABREQUIM', 'RETENTOR VIRABREQUIM']},
            'retentores_comando_valvula': {'codigo': '0047', 'itens': ['RETENTOR VALVULA ADMISSAO', 'RETENTOR VALVULA', 'KIT RETENTOR COMANDO VALVULA', 'RETENTOR ARVORE', 'RETENTOR COIFA DIRECIONAL', 'RETENTOR COMANDO', 'RETENTOR HASTE VALVULA', 'RETENTOR SEMI ARVORE']},
            'retentores_caixa_cambio': {'codigo': '0048', 'itens': ['RETENTOR CAIXA CAMBIO', 'RETENTOR CAIXA TRACAO', 'RETENTOR CAIXA TRACAO', 'RETENTOR CAMBIO SEMI EIXO', 'RETENTOR CAMBIO', 'RETENTOR COROA LATERAL', 'RETENTOR DIFERENCIAL', 'RETENTOR PINHAO', 'RETENTOR RABETA', 'RETENTOR SAIDA CAMBIO', 'RETENTOR SAIDA CAIXA', 'RETENTOR SAIDA DIFERENCIAL', 'RETENTOR TAMPA LATERAL CAMBIO', 'RETENTOR TRAMBULADOR', 'RETENTOR TRANSMISSAO']},
            'retentores_motor': {'codigo': '0141', 'itens': ['KIT RETENTOR MOTOR', 'RETENTOR BOMBA INJETORA', 'RETENTOR BOMBA VACUO', 'RETENTOR MANCAL ALTERNADOR', 'RETENTOR CAIXA MOTOR', 'RETENTOR POLIA MOTOR', 'RETENTOR MOTOR', 'RENTENTO DIAT COMANDO', 'RETENTOR DISTRIBUIDOR', 'RETENTOR CORREIA ']},
            'vedacao': {'codigo': '0114', 'itens': ["BUCHA VEDACAO", 'GUARNICAO BUCHA VEDACAO', 'GUARNICAO', 'GAXETA', 'JUNTA BOIA COMB', 'JUNTA GUARNICAO', 'KIT PESCOCEIRA', 'KIT SELO COMANDO', 'KIT VEDACAO FLANGE', 'SELO AGUA', 'SELO MOTOR', 'SELO BLOCO MOTOR', 'TAPA PO CAIXA', 'VEDACAO JUNTA', 'VEDACAO MONOPONTO', 'VEDADOR BRACO', 'VEDADOR HASTE', 'VEDADOR RADIADOR', ]},
        }
    },
    'lubrificacao': {
        'codigo': '0028',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ALONGADOR VARETA', 'FLEXIVEL FILTRO OLEO', 'PESCADOR BOMBA OLEO', 'PESCADOR CARTER OLEO', 'RESPIRO OLEO']},
            'bombas_oleo': {'codigo': '0049', 'itens': ['BOMBA OLEO', 'CORPO BOMBA OLEO']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM BOMBA OLEO']},
            'reservatorios_oleo': {'codigo': '0050', 'itens': []},
            'vareta_oleo': {'codigo': '0155', 'itens': ['VARETA OLEO', 'VARETA NIVEL OLEO', 'VARETA NIVEL TRANSMISSAO']},
        }
    },
    'mangueiras': {
        'codigo': '0029',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['MANGEIRA TAMPA VALV CONEXAO', 'MANGUEIRA DIRECAO HIDR', 'PRESIL']},
            'mangueiras_ar_condicionado': {'codigo': '0051', 'itens': ['MANGUEIRA AR COND', 'MANGUEIRA AR CONDICIONADO', 'MANGUEIRA EVAPORADOR AR COND', 'MANGUEIRA AQUECEDOR AR COND']},
            'mangueiras_aquecimento': {'codigo': '0052', 'itens': ['MANGUEIRA AQUECEDOR', 'MANGUEIRA AQUECIMENTO', 'MANGUEIRA ENTR AQUECEDOR', 'MANGUEIRA ENTRADA AQUEC', 'MANGUEIRA ENTRADA AQUECEDOR', 'MANGUEIRA ENTRADA AQUECIMENTO', 'MANGUEIRA PRE AQUEC', 'MANGUEIRA SAIDA AQUEC', 'MANGUEIRA TUBO AQUEC', 'MANGUEIRA VALV AQUECIMENTO']},
            'mangueiras_carcacas': {'codigo': '0146', 'itens': ['MANGUEIRA ANTI CHAMA', 'MANGUEIRA CARCACA', 'MANGUEIRA CORPO VALV TERMOSTATICA', 'MANGUEIRA ENTRADA AR CHAMA', 'MANGUEIRA COLETOR ANTI CHAMA', 'MANGUEIRA COLETOR CHAMA', 'MANGUEIRA COLETOR VALV TERMOSTATICA', 'MANGUEIRA RESPIRO ANTI CHA', 'MANGUEIRA VALV TERMOST', 'MANGUEIRA VALV REG PRESSAO ANTI CHAMA']},
            'mangueiras_combustivel': {'codigo': '0053', 'itens': ['MANGUEIRA BOCAL COMB', 'MANGUEIRA BOCAL TANQUE', 'MANGUEIRA BOMBA INJ COMB', 'MANGUEIRA BOMBA LIGACAO BICO INJETOR', 'MANGUEIRA COMBUSTIVEL', 'MANGUEIRA ELETROVALVULA', 'MANGUEIRA CANISTER', 'MANGUEIRA COLETOR', 'MANGUEIRA RETORNO']},
            'mangueiras_agua': {'codigo': '0054', 'itens': ['MANGUEIRA AGUA AQUECEDOR', 'MANGUEIRA AGUA MOTOR', 'MANGUEIRA AGUA QUENTE', 'MANGUEIRA ALIMENTACAO AGUA', 'MANGUEIRA RESERV', 'MANGUEIRA RESERV AGUA', 'MANGUEIRA BOMBA AGUA', 'MANGUEIRA BOMBA DAGUA', 'MANGUEIRA BOMBA HIDR', 'MANGUEIRA DAGUA', 'MANGUEIRA DUTO RIGIDO BOMBA AGUA', 'MANGUEIRA ENTRADA AGUA AQUECIMENTO', 'MANGUEIRA ENTRADA BOMBA AGUA', 'MANGUEIRA ENTRADA AGUA', 'MANGUEIRO ENVIO DAGUA', 'MANGUEIRA FLUXO AGUA', 'MANGUEIRA HIDRAULICO', 'MANGUEIRA LIGACAO BOMBA AGUA', 'MANGUEIRA LIGACAO AGUA', 'MANGUEIRA RETORNO AGUA', 'MANGUEIRA SAIDA AGUA', 'MANGUEIRA ARREFECIMENTO', 'MANGUEIRA BOMBA CABECOTE', 'MANGUEIRA BOMBA TUBO REFRIGERA', 'MANGUEIRA COLETOR AGUA', 'MANGUEIRA COLETOR DUTO', 'MANGUEIRA COLETOR TUBO AGUA', 'MANGUEIRA CURVA SUP RADIADOR', 'MANGUEIRA EXPANSAO RADIADOR', 'MANGUEIRA DESCARGA', 'MANGUEIRA RADIADOR', 'MANGUEIRA TERMOSTATO', 'MANGUEIRA DRENO', 'MANGUEIRA DUTO RADIADOR', 'MANGUEIRA ENTRADA TUBO REFRIGERACAO', 'MANGUEIRA FLANGE AO RADIADOR', 'MANGUEIRA INFERIOR', 'MANGUEIRA INF RADIADOR', 'MANGUEIRA INFERIOR RADIADOR', 'MANGUEIRA SUP RADIADOR', 'MANGUEIRA SUPERIOR', 'MANGUEIRA SUPERIOR RADIADOR', 'MANGUEIRA TORNEIRA', 'MANGUEIRA TUBO BOMBA AGUA', 'MANGUEIRA TUBO CAMARA TERMOST', 'MANGUEIRA TUBO CURVO SUP RADIADOR', 'MANGUEIRA TUBO DAGUA', 'MANGUEIRA TUBO REFRIG', 'MANGUEIRA TUBO RESERVATORIO', 'MANGUEIRA TUBO RESFRIADOR', 'MANGUEIRA TUBO RETORNO AGUA', 'MANGUEIRA TUBO CONEX AGUA', 'MANGUEIRA VALV TERMOST AGUA']},
            'mangueiras_ar_motor': {'codigo': '0085', 'itens': ['DUTO FILTRO AR', 'MANGUEIRA FILTRO AR', 'DUTO AR ADMISSAO', 'KIT MANGUEIRA AR QUENTE', 'MANGUEIRA ADAPTACAO VALV', 'MANGUEIRA ADMISSAO', 'MANGUEIRA AR QUENTE', 'MANGUEIRA COLETOR ADM', 'MANGUEIRA COLETOR ADMISSAO', 'MANGUEIRA CONECTOR AQUEC', 'MANGUEIRA FILTRO AR', 'MANGUEIRA DUTO FILTRO', 'MANGUEIRA DUTO RIGIDO COLETOR', 'MANGUEIRA AR QUENTE', 'MANGUEIRA FILTRO COLETOR', 'MANGUEIRA FITRO AR', 'MANGUEIRA LIGACAO COLETOR ADMISSAO', 'MANGUEIRA RESPIRO MOTOR', 'MANGUEIRA LIGACAO VALV COLETOR', 'MANGUEIRA MOTOR AR QUENTE' ,'MANGUEIRA RESPIRO', 'MANGUEIRA RETORNO AR', 'MANGUEIRA RETORNO TURBO', 'MANGUEIRA SAIDA AR', 'MANGUEIRA SISTEMA AR', 'MANGUEIRA ADMISSAO BOMBA', 'MANGUEIRA BOMBA VACUO', 'MANGUEIRA CABECOTE CARBURADOR', 'MANGUEIRA CARBURADOR', 'MANGUEIRA COLETOR ADMISSAO OLEO', 'MANGUEIRA COLETOR ADMISSAO', 'MANGUEIRA COLETOR ADMISSAO AGUA', 'MANGUEIRA COLETOR CABECOTE', 'MANGUEIRA COLETOR CONEXAO', 'MANGUEIRA AR COLETOR', 'MANGUEIRA TUBO COLETOR', 'MANGUEIRA COMPENSACAO MARCHA LENT', 'MANGUEIRA CONJUNTO MENOR', 'MANGUEIRA DO INTERCOOLER TURBO', 'MANGUEIRA ENTRADA DISTRIBUICAO', 'MANGUEIRA SERVO FREIO', 'MANGUEIRA RESPIRO MOTOR', 'MANGUEIRA TUBO LIGAC SENSOR PALIO', 'MANGUEIRA TUBO VENTILACAO MOTOR', 'MANGUEIRA TURBO RESFRIADOR', 'MANGUEIRO FILTRO AO EXAUSTOR', 'MANGUEIRA TUBO DIANTEIRO', 'MANGUEIRA VACUO', 'MANGUEIRA VALVULA AR', 'MANGUEIRA VALVULA VAPOR', 'MANGUEIRA VALV RESPIRO', 'MANGUEIRA VENT', 'MANGUEIRA VENT BLOCO', 'MANGUEIRA VENTILACAO', 'MANGUEIRA VENTILACAO MOTOR', 'MANGUEIRA VENTILADOR']},
            'mangueiras_oleo': {'codigo': '0086', 'itens': ['MANGUEIRA BLOCO OLEO', 'MANGUEIRA RESPIRO OLEO', 'MANGUEIRA LUBRIFICACAO BOMBA DIRECAO', 'MANGUEIRA RETORNO OLEO', 'MANGUEIRA FILTRO OLEO', 'MANGUEIRA ENTRE TUBO E RADIADOR OLEO', 'MANGUEIRA LIGACAO CABECOTE', 'MANGUEIRA RAD OLEO', 'MANGUEIRA RESFRIADOR OLEO', 'MANGUEIRA RESFRIAMENTO COLETOR', 'MANGUEIRA RESFRIAMENTO OLEO', 'MANGUEIRA RESPIRO OLEO', 'MANGUEIRA TAMP VALV', 'MANGUEIRA TUBO RADIADOR OLEO']},
            'mangueiras_metro': {'codigo': '0145', 'itens': ['MANGUEIRA METRO', 'MANGUEIRA METRO COMBUSTIVEL']},
            'bocais': {'codigo': '0097', 'itens': ['BOCAL TANQUE']},
        }
    },    
    'motor': {
        'codigo': '0030',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BUCHA ARRANQUE', 'BALANCIM', 'DEFLETOR CARTER', 'GARFO PARTIDA', 'GUIA VALVULA', 'KIT MOTOR', 'PULA MACACO', 'PARAFUSO CABECOTE', 'PARAFUSO COLETOR ADMISSAO', 'PARAFUSO COM PORCA MOTOR', 'PARAFUSO MOTOR', 'PARAFUSO TAMPA VALV', 'PASTILHA REGULAGEM', 'PENEIRA CARTER', 'PORCA VOLANTE', 'CHAPA FIXACAO SUPORTE MOTOR']},
            'cabecotes': {'codigo': '0055', 'itens': ['CABECOTE', 'CABECOTE MOTOR']},
            'comandos': {'codigo': '0118', 'itens': ['COMANDO', 'EIXO COMANDO', 'GAIOLA COMANDO', 'EIXO COMANDO VALV', 'KIT COMANDO']},
            'coxins': {'codigo': '0078', 'itens': ['COXIM MOTOR', 'COXIM DIANTEIRO MOTOR', 'COXIM CENTRAL MOTOR', 'KIT COXIM MOTOR', 'COXIM TIRANTE MOTOR']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM VIRABREQUIM', 'ENGRENAGEM CORPO BORBOLETA']},
            'virabrequins': {'codigo': '0056', 'itens': []},
            'kit_corrente': {'codigo': '0144', 'itens': ['KIT CORRENTE/TENSOR/ENGREN', 'KIT DISTRIB']},
            'carteres': {'codigo': '0057', 'itens': ['CARTER']},
            'bronzinas': {'codigo': '0100', 'itens': ['BRONZINA','BRONZINA DE BIEL', 'BRONZINA MANCAL']},
            'tuchos': {'codigo': '0103', 'itens': ['BUCHA POSTERIOR ARVORE', 'CAPA TUCHO', 'KIT TUCHO VELA', 'TUCHO HIDRAULICO', 'TUCHO VALVULA', 'VARETA TUCHO']},
            'parafuso_cabecote': {'codigo': '0105', 'itens': ['BUCHA PRISIONEIRO CABECOTE', 'JOGO PARAFUSO CABECOTE','PARAFUSO CABECOTE', 'PARAFUSO PRISIONEIRO']},
            'corpo_borboleta': {'codigo': '0123', 'itens': ['CORPO BORBOLETA']},
            'jogo_pistoes': {'codigo': '0142', 'itens': ['JOGO MOTOR PISTAO CAMISA', 'SUPER KIT MOTOR ']},
            'valvulas_motor': {'codigo': '0153', 'itens': ['VALVULA ADMISSAO', 'VALVULA ESCAPAMENTO', 'VALVULA ESCAPE', 'VALVULA FILTRO AR', 'VALVULA MAXIMA CARB', 'VALVULA MOTOR ESCAP', 'VALVULA RESPIRO MOTOR', 'VALVULA RESPIRO TANQUE', 'VALVULA TERMOSTATICA', 'VALVULA ADMISSAO']},
        }
    },
    'reparos': {
        'codigo': '0031',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ["ACOPLAMENTO COLETOR ADMISSAO", "ACOPLAMENTO DIRECAO", "ACOPLAMENTO VISOCOSO", 'ADAPTADOR BICO INJETOR', "ADAPTADOR COLETOR ADMISSAO", 'ARTICULADOR DIRECAO', 'BUCHA SUPORTE MOTOR', 'CALCO SUPORTE FRONTAL MOTOR', "REPARO COLETOR ADMISSAO", "REPARO DIRECAO", "ADAPTADOR MOTOR MAQ VIDRO", 'BUCHA RETORNO PEDAL', 'EIXO ACELERADOR', 'FILTRO BICO ANE', 'JOGO MOLA TRAS BENDIX', 'KIT BUCHA VEDACAO', 'KIT BUCHA MOTOR', 'KIT CALCO MOLA', 'KIT CALOTA CUBO', 'KIT PINO GUIA VOLANTE', 'KIT REPARO BIELETA', 'KIT REPARO COLUNA DIRECAO', 'KIT REPARO CREMALHEIRA', 'KIT REPARO FEIXE MOLA', 'KIT REPARO SETOR', 'KIT REPARO ROLAMENTO', 'KIT ROLAMENTO REPARO BANDEJA', 'KIT SUSPENSAO TRAS', 'PINHAO VELOCIMETRO', 'PINO PEDAL EMBREAGEM', 'PINO ELAST ALAVANCA CAMB', 'PINO FIXACAO HASTE', 'PINO PASTILHA', 'PINO PEDAL' 'CONJUNTO VARETA TRAVA PINO FECHADURA', 'KIT REPARO CILINDRO MACANETA']},
            'kit_reparo_aneis': {'codigo': '0139', 'itens': ['KIT ANEIS', 'KIT ANEL', 'KIT ARRUELA EMBUCHAMENTO', 'REPARO ANEL']},
            'kit_reparo_cambio': {'codigo': '0059', 'itens': ['ACOPLAMENTO HASTE TRAMBULADOR', 'ACOPLAMENTO HASTE LIGACAO',"ACOPLAMENTO VARAO CAMBIO", 'ARTICULACAO CABO ENGATE', 'ARTICULADOR CABO ENGATE', 'LIAME TRAMB', "REPARO VARAO CAMBIO", 'BUCHA ALAVANCA CAMBIO', 'BUCHA REPARO ALAVANCA', 'BORRACHA/REPARO TRAMBULADOR', 'CACHORRINHO REPARO ANEIS', 'BUCHA CABO MARCHA', 'BUCHA PEDAL EMBREAGEM', 'BUCHA PRETA TRAMBULADOR', 'BUCHA SELETOR MARCHA', 'BUCHA TRAMBULADOR', 'BUCHA VARAO CAMBIO', 'CONJUNTO KIT REPARO PEDAL', 'CATRACA ACIONADOR EMBREAGEM', 'CONJUNTO AGULHA MOLA MARCHA', 'COROA VELOCIMETRO', 'EIXO PINHAO VELOCIMETRO', 'ENGATE TRAMBULADOR', 'KIT ARTICULADOR MARCHA', 'KIT BUCHA TRAMBULADOR', 'KIT HASTE SELETORA', 'KIT PEDAL ACELERADOR', 'KIT PINO MOLA CAMBIO', 'KIT REPARO ARTICULACAO TRAMB', 'KIT REPARO CABO CAMBIO', 'KIT REPARO CABO COMANDO', 'KIT REPARO CABO EMBREAGEM', 'KIT MOLA COMPLETO TRAMBULADOR', 'KIT REPARO GARFO EMBREAGEM', 'KIT REPARO HOMOCINETICA', 'KIT REPARO JUNTA HOMOCI', 'KIT REPARO TRAMBULADOR', 'KIT SETOR CAIXA', 'KIT SUPORTE TRAMBULADOR', 'KIT TENSOR DIANT', 'KIT TENSOR SUSP', 'KIT SUPORTE TRAMBULADOR', 'KIT TRAMBULADOR', 'LIMITADOR TORCAO', 'PEDAL ACELERADOR', 'KIT COROA PINHAO', 'LUVA DIFERENCIAL', 'LUVA PINHAO DIFERENCIAL', 'PINHAO COROA', 'PLANETARIA', 'REPARO BARRA TORCAO', 'REPARO CABO CAMBIO', 'REPARO CABO EMBREAGEM', 'REPARO CAIXA DIFERENCIAL', 'REPARO DIFERENCIAL', 'REPARO PLANETARIO', 'REPARO TRAMBULADOR', 'REPARO TRIZETA', 'SUB CONJUNTO TRAMBULADOR', 'TIRANTE ACIONAMENTO EMBREAGEM', 'TIRANTE COMANDO CAMBIO', 'TRAMBULADOR', 'CHAPA ENCOSTO PEDAL EMBREAGEM', 'CHAPA GUIA ALAVANCA CAMBIO']},
            'kit_reparo_freio': {'codigo': '0140', 'itens': ['CONJUNTO REPARO PASTILHA', 'KIT REGULADOR DO FREIO', 'JOGO MOLA FREIO', 'JOGO REGULADOR FREIO', 'KIT PISTAO FREIO', 'KIT REPARO PATIM', 'KIT REPARO SAPATA', 'KIT EMBUCHAMENTO', 'REGULADOR FREIO', 'REGULADOR PATIM', 'REPARO CENTRAL PATIM', 'REPARO FREIO DIANT', 'REPARO FREIO', 'REPARO PATIM', 'REPARO PEDAL FREIO', 'REPARO SAPATA', 'REPARO VALV SERVO FREIO']},
            'kit_reparo_eletrica': {'codigo': '0205', 'itens': ['KIT REPARO BICO INJETOR', 'REPARO AUTOMATICO PARTIDA' , 'REPARO BICO INJETOR', 'REPARO FLAUTA INJETOR', 'REPARO INJETOR', 'REPARO MOTOR PARTIDA', 'REPARO PARTIDA PORTA ESCOVA', 'REPARO PRESSAO']},
            'kit_reparo_ferragem': {'codigo': '0231', 'itens': ['BUCHA DOBRADICA', 'BUCHA MACANETA EXTERNA', 'BUCHA TAMPA CACAMBA', 'BUCHA TRAVA ENCOSTO', ]},
            'kit_reparo_homocinetica': {'codigo': '0058', 'itens': ['KIT REPARO HOMOCINETICA']},
            'kit_reparo_maquina_vidro': {'codigo': '0253', 'itens': ['ARRASTE MAQ VIDRO', 'ARRASTE MAQUINA VIDRO', 'KIT REPARO MAQUINA VIDRO', 'PONTEIRA CABO MAQUINA VIDRO', 'ROLDANA MAQUINA VIDRO', 'SUPORTE ARRASTE MAQUINA VIDRO', 'SUPORTE ROLDANA MAQUINA VIDRO']},
            'kit_reparo_pincas': {'codigo': '0077', 'itens': ['BUCHA PINCA', 'KIT PINO PINCA', 'REPARO PINCA', 'REPARO PINCA FREIO', 'REPARO PINCA VEDACAO']},
            'kit_reparo_setor': {'codigo': '0088', 'itens': ['ACOPLAMENTO SETOR', 'GUIA SETOR DIRECAO', 'REPARO COLUNA DIR', 'REPARO CIL RODA', 'REPARO CILINDRO MESTRE', 'REPARO CILINDRO RODA', 'REPARO COLUNA', 'REPARO PARCIAL CIL RODA', 'REPARO SETOR']},
            'kit_reparo_suspensao': {'codigo': '0148', 'itens': ['REPARO BANDEJ', 'REPARO BANDEJ EIXO', 'REPARO BATENTE BANDEJ', 'REPARO BRACO OSCILANTE', 'REPARO CAPA EIXO', 'REPARO EIXO TRAS', 'CHAPA SUPERIOR AMORTECEDOR']},
            'alavancas': {'codigo': '0090', 'itens': ['ALAVANCA ACIONADORA', 'ALAVANCA CAMBIO', 'ALAVANCA EMB', 'ALAVANCA EMBREAGEM', 'ALAVANCA ENGATE', 'ALAVANCA ENGRENAGEM', 'ALAVANCA FREIO MAO', 'ALAVANCA FREIO TRAS', 'ALAVANCA GARFO PARTIDA', 'ALAVANCA INIBIDORA', 'ALAVANCA LIGACAO', 'ALAVANCA MARCHA', 'ALAVANCA PATIM', 'ALAVANCA REG', 'ALAVANCA REGULADO', 'ALAVANCA SELETORA', 'ALAVANCA TRAMBULADOR', 'BUCHA LATERAL ALAVANCA', 'HASTE CABO EMB', 'HASTE DESLIZ MARCH', 'HASTE DELIZ RE', 'HASTE ALAV CAMB', 'HASTE EMB', 'HASTE FREIO', 'HASTE FREIO TRASEIRO', 'HASTE PORSCHE', 'HASTE TRAMB', 'HASTE PATIM FREIO', 'JOGO ALAVANCA ACIONAMENTO', 'KIT ALAVANCA ACELERADOR', 'KIT ALAVANCA CAMBIO', 'KIT ALAVANCA CARBU', 'KIT REPARO ALAVANCA', 'KIT REPARO CUPULA ALAVANCA', 'LIMITADOR ALAVANCA', 'MOLA ALAVANCA SELETORA', 'MOLA ALAVANCA CAMBIO', 'REPARO ALAVANCA CAMBIO', 'REPARO ALAVANCA FREIO', 'REPARO BUCHA VARAO', 'REPARO HASTE ALAVANCA', 'ROTULA ALAVANCA CAMBIO', 'TIRANTE EXTERNO CAMBIO', 'TIRANTE LIGACAO ARTICULACAO', 'TIRANTE LIGACAO CAMBIO', 'TIRANTE SUSP TRAS', 'TRAVA ALAVANCA CAMBIO ', 'VARAO EMBREAGEM', 'SUPORTE ALAVANCA FREIO', 'VARAO CAMBIO']},
            'molas_reparo': {'codigo': '0147', 'itens': ['MOLA EXTERNA VALVULA', 'MOLA ATUACAO VALVULA PROPO FREIO', 'MOLA RETORNO FREIO', 'MOLA COLAR EMBREAGEM', 'MOLA ACELERADOR', 'MOLA BUZINA', 'MOLA RETENCAO', 'MOLA RETORNO', 'MOLA PATIM', 'MOLA HASTE ACIONAMENTO', 'MOLA INTERNA VALVULA', 'MOLA VALVULA']},
            'valvulas_reparo': {'codigo': '0154', 'itens': ['VALVULA AGULHA', 'VALVULA ALIVIO PRESSAO', 'VALVULA ANTI CHAMA', 'VALVULA AR QUENTE', 'VALVULA DE CILINDRO', 'VALVULA CONTROLE AQUECEDOR', 'VALVULA COMPRESSAO AR COND', 'VALVULA OLEO', 'VALVULA EQUALIZADORA', 'VALVULA PROPORCIONADORA', 'VALVULA SERVO FREIO', 'VALVULA SOLENOIDE', 'VALVULA CANISTER', 'VALVULA COMUTADORA', 'VALVULA DE MAXIMA', 'VALVULA DRENO PORTA', 'VALVULA SERVO AR', 'VALVULA SANGRADOR FREIO', 'VALVULA RESTRICAO GARGALO', 'VALVULA PRESSAO PNEUS', '']},
        }
    },
    'rolamentos_tensores_polias': {
        'codigo': '0032',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['ROLAMENTO CAMBIO', 'BUCHA AGULHA', 'BUCHA AGULIA', 'KIT ROLAMENTO', 'PARAFUSO ROLAM EST CORREIA', 'ROLAMENTO BOMBA AGUA', 'ROLAMENTO DO ROLO CILINDRICO', 'ROLAMENTO PRIZ']},
            'rolamentos_ar_condicionado': {'codigo': '0150', 'itens': ['ROLAMENTO AR CONDICIONADO', 'ROLAMENTO ESTIC AR', 'ROLAMENTO ESTIC CORR AR']},
            'rolamentos_roda': {'codigo': '0061', 'itens': ['BUCHA ROLAMENTO DIRECAO', 'KIT ROLAMENTO RODA TRAS', 'ROLAMENTO QUADRO SUSPENSAO', 'ROLAMENTO EIXO', 'ROLAMENTO SEMI EIXO', 'ROLAMENTO AMORT', 'ROLAMENTO AMORTECEDOR', 'ROLAMENTO CONICO', 'ROLAMENTO COLUNA DIRECAO', 'ROLAMENTO COXIM AMORT', 'ROLAMENTO CUBO DIANT', 'ROLAMENTO DE EIXO', 'ROLAMENTO EIXO', 'ROLAMENTO RODA', 'ROLAMENTO DIANTEIRO', 'ROLAMENTO SUSPENSAO']},
            'rolamentos_motor': {'codigo': '0062', 'itens': ['ROLAMENTO ESTICADOR', 'ROLAMENTO MOTOR', 'ROLAMENTO ALTERNADOR', 'ROLAMENTO CORREIA ESTICADORA DO ALTERNADOR', 'ROLAMENTO ESTICADOR', 'ROLAMENTO ESTIC ALT', 'ROLAMENTO ESTIC CORR', 'ROLAMENTO ESTIC', 'ROLAMENTO ESTICADOR CORREIA ALTERNADOR', 'ROLAMENTO ESTICADOR ALTERNADOR', 'ROLAMENTO ESTICADOR CORREIA', 'ROLAMENTO COMANDO', 'ROLAMENTO CORREIA COMANDO', 'ROLAMENTO TENSOR', 'ROLAMENTO TENSOR CORREIA']},
            'rolamentos_embreagem': {'codigo': '0149', 'itens': ['ROLAMENTO EMBREAGEM', 'ROLAMENTO CAMBIO', 'ROLAMENTO CAIXA CAMBIO', 'ROLAMENTO CARDAN', 'ROLAMENTO PINHAO', 'ROLAMENTO AGULHA', 'ROLAMENTO ATUADOR EMBREAGEM', 'ROLAMENTO COIFA', 'ROLAMENTO DIFERENCIAL', 'ROLAMENTO LATERAL COROA CAIXA', 'ROLAMENTO SATELITE', 'ROLAMENTRO TRASEIRO CAIXA', 'ROLAMENTO VISCOSA']},
            'tensores': {'codigo': '0063', 'itens': ['ROLO ROLAMENTO DAMPER', 'TENSOR CORREIA ALTERNADOR', 'TENSOR CORREIA COMANDO', 'TENSOR ESTICADOR']},
            'polias': {'codigo': '0064', 'itens': ['CHAVETA FRESADA POLIA', 'POLIA ALTERNADOR', 'POLIA ALT', 'POLIA AUXILIAR', 'POLIA BOMBA AGUA', 'POLIA BOMBA DIR', 'POLIA CORREIA', 'POLIA DIRECAO', 'POLIA VENTILADOR', 'POLIA RODA LIVRE', 'POLIA TENSOR', 'POLIA VIRAB', 'POLIA VIRABREQUIM', 'SOBREPOLIA AR COND', 'POLIA MANIVELA MOTOR']},
        }
    },
    'suspensao': {
        'codigo': '0033',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['EMBUCHAMENTO', 'CALCO AJUSTE', 'CALCO AMORT', 'CALCO BATENT', 'CALCO CAMBAGEM', 'CUPILHA', 'EIXO BANDEJA TRAS', 'EIXO TENSOR', 'ESPACADOR ANEL VEDADOR', 'ESPACADOR ROLAMENTO', 'FACAO SUSPENS', 'MONTANTE', 'PARAFUSO BANDEJA', 'PARAFUSO CAMBAGEM', 'PARAFUSO EIXO TRAS', 'PORCA AMORTECEDOR', 'SUPORTE AMORTECEDOR DIANT', 'TELEFONE PINO ROLAMENTO', 'TIRANTE SUSPENSAO']},
            'buchas_suspensao': {'codigo': '0065', 'itens': ['BARRA TORCAO', 'BUCHA BAND SUSP', 'BUCHA BARRA ESTAB', 'BUCHA BANDEJA DIANT', 'BUCHA BANDEJA SUSPENSAO', 'BUCHA AGREGADO', 'BUCHA ALGEMA BARRA', 'BUCHA ALT SUP', 'BUCHA ALTERNADOR', 'BUCHA AMORT', 'BUCHA AMORT DIANT', 'BUCHA AMORTEC', 'BUCHA AMORTECEDOR', 'BUCHA AR COND', 'BUCHA ARTIC EIXO', 'BUCHA ARTICULACAO', 'BUCHA BAND', 'BUCHA BANDEJA', 'BUCHA BARR ESTAB', 'BUCHA BARRA ESTAB', 'BUCHA BARRA LIGACAO', 'BUCHA BARRA TENS SUSP', 'BUCHA BARRA TORCAO' 'BUCHA BIELETA', 'BUCHA CALCO TRAVESSA', 'BUCHA CENTRAL BANDEJA', 'BUCHA COXIM', 'BUCHA EIXO', "BUCHA ESTAB", 'BUCHA ESTABILIZADORA', 'BUCHA FEIXE MOLA', 'BUCHA MANGA EIXO', 'BUCHA HAST BAND', 'BUCHA INF AMOR', 'BUCHA INFERIOR BANDE', 'BUCHA INFERIOR AMORT', 'BUCHA INFERIOR JUMELO', 'BUCHA JUMELO', 'BUCHA MAIOR', 'BUCHA MENOR', 'BUCHA MOLA', 'BUCHA OVAL EIXO', 'BUCHA TRAS BAND', 'BUCHA PONTA BANDEJA', 'BUCHA SUP ALGEMA', 'BUCHA SUP AMOR', 'BUCHA SUPERIOR BAND', 'BUCHA SUPERIOR JUMELO', 'BUCHA SUSP', 'BUCHA SUSPEN', 'BUCHA SUSPENSAO', 'BUCHA TENSO', 'BUCHA TENSOR SUS', 'BUCHA TERMINAL EIXO', 'BUCHA TIRANTE', 'BUCHA TARS BAND', 'BUCHA TRAS BRAC', 'BUCHA TRAS EIXO', 'BUCHA TRAS FEIXE MOLA', 'BUCHA TRAS SUSP', 'BUCHA TRAS BAND', 'BUCHA TRASEIRA BANDEJA', 'BUCHA TRAV EIXO', 'BUCHA QUADRO', 'BUCHA SUPERIOR QUADRO', 'BUCHA TRAS QUADRO', 'CAPA AMORTECE DIAN', 'CALCO CARROCERIA', 'FLUTOBLOC', 'KIT BUCH SUSP', 'KIT BORRACHA BARRA ESTAB', 'KIT BUCHA ACAB', 'KIT BUCHA BARRA ESTAB', 'KIT BUCHA BRACO', 'KIT BUCHA ESTAB', 'KIT BUCHA ESTABILIZADORA', 'KIT BUCHA FEIXE MOLA', 'KIT BUCHA TIRANTE', 'KIT TIRANTE DIANT', 'KIT TIRANTE']},
            'amortecedores': {'codigo': '0066', 'itens': ["AMORT DIANT", "AMORTECEDOR DIANT", "AMORTECEDOR REMAN", "AMORTECEDOR TRAS", "AMORTECEDOR TRASEIRO",]},
            'coifas': {'codigo': '0128', 'itens': ['COIFA AMORT', 'GUARDA PO AMORT', 'KIT COIFA AMORT', 'KIT COIFA AMORTECEDOR', 'KIT COIFA BATENTE AMORTECEDOR DIANTEIRO', 'KIT COIFA AMORTECEDOR TRASEIRO', 'KIT COIFA BATENTE DIANTEIRO', 'KIT COIFA BATENTE AMORTECEDOR', 'KIT COIFA BATENTE', 'KIT COIFA BATENTE AMORT', 'KIT COIFA BATENTE DIANTEIRO', 'KIT COIFA BATENTE', 'KIT COIFA BATENTE COXIM AMORT', 'PAR AMORTECEDOR DIANTEIRO', 'PAR AMORTECEDOR REMANUFATURADO' ]},
            'coxins': {'codigo': '0078', 'itens': ['CALCO AMORTECE', 'SEDE ROLAMENTO SUSP', 'COXIM AMORT', 'COXIM AMORTECEDOR', 'COXIM BR OSCI', 'COXIM BRACO OSCIL', ' COXIM CABINE', 'COXIM LIMITADOR TORCAO', 'COXIM ESTABILIZADOR', 'COXIM SUSP', 'CAPA SUSPENSAO', 'COXIM CABINE', 'COXIM LIMITADOR SUSPENSAO', 'COXIM COM ROLAMENTO AMORT', 'COXIM TRASEIRA BANDEJA']}, 
            'bieletas': {'codigo': '0079', 'itens': ['BIELETA', 'BIELETA BARRA ESTAB', 'BIELETA BARRA ESTABILIZADORA', 'BIELETA DIANT', 'BIELETA ESTAB', 'BIELETA ESTABILIZADORA', 'BIELETA SUSP', 'BIELETA SUSPENSAO', 'BIELETA TRAS']},
            'bandejas': {'codigo': '0080', 'itens': ['BAND SUSP SUP', 'BANDEJA', "BANDEJA DIANT", 'BANDEJA DIANTEIRA', 'BANDEJA INFERIOR', 'BANDEJA SUS', 'BANDEJA SUSPENSAO', 'SUPORTE BANDEJA DIANTEIRA']},
            'eixos_suspensao': {'codigo': '0132', 'itens': ['EIXO TRAS', 'PONTA EIXO', 'EIXO DIANTEIRO']},
            'kit_batentes_amortecedor': {'codigo': '0081', 'itens': ['BATENTE AMORT', 'BATENTE AMORTECEDOR', 'BATENTE BANDEJA', 'BATENTE BRACO', 'BATENTE DE MOLA', 'BATENTE DIANT', 'BATENTE EIXO', 'BATENTE FEIXE MOLA', 'BATENTE INF', 'BATENTE INFERIOR', 'BATENTE MOLA', 'BATENTE SUP', 'BATENTE SUSP', 'BATENTE COIFA', 'BOLACHA SANTA FE', 'BORRACHA BARRA ESTA', 'BORRACHA HASTE VALVULA', 'BORRACHA LIGACAO BARRA EST', 'KIT AMORTECEDOR', 'KIT AMORT DIANT', 'KIT AMORTECEDOR DIANT', 'KIT AMORTECEDOR SUSP', 'KIT AMORTECEDOR TRAS', 'KIT BATENTE AMORT', 'KIT BATENTE AMORTECEDOR', 'KIT BATENTE/COIFA', 'KIT DO AMORTECEDOR']},
            'molas': {'codigo': '0115', 'itens': ['MOLA SUSPENSAO', 'FEIXE MOLA', 'MOLA DIANT', 'MOLA DIANTEIRA', 'MOLA SUSPENSAO DIANTEIRA', 'MOLA SUSPENSAO TRASEIRA', 'MOLA TRAS', 'MOLA TRASEIRA', 'PAR MOLA TRAS']},
            'pratos': {'codigo': '0104', 'itens': ['ASSENTO SUPERIOR MOLA', 'KIT PRATO AMORTECEDOR', 'KIT PRATO LOCALIZADOR BATENTE', 'PRATO AMORTECEDOR', 'PRATO COXIM AMORT', 'PRATO LOCALIZADOR BATENTE DIANT', 'PRATO MOLA DIANT', 'PRATO MOLA VAL', 'PRATO SUPERIOR AMORTECEDOR DIANT', 'PRATO SUPERIOR MOLA DIANT']},
            'barra_estabilizadora': {'codigo': '0095', 'itens': ['BARRA ESTABILIZADORA', 'SUPORTE BARRA ESTABILIZADORA']},
            'kit_barra_estabilizadora': {'codigo': '0096', 'itens': ['KIT BARRA ESTAB', 'KIT BARRA ESTABILIZADORA', 'KIT ESTABILIZADOR']},
            'cubos_roda': {'codigo': '0076', 'itens': ['CUBO RODA', 'CUBO RODA DIANTEIR', 'CUBO RODA TRASEIRO', 'CALOTA CUBO RODA', 'CALOTA FERRO CUBO RODA', 'CA']},
        }
    },
    'tampas': {
        'codigo': '0123',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['TAMPA', 'TAMPA MANCAL', 'TAMPA AR QUENTE', 'TAMPA BLOCO CABECOTE', 'TAMPA TORCAO', 'TAMPA CAIXA AR', 'TAMPA CAIXA FILTRO AR', 'TAMPA CORRENTE MOTOR', 'TAMPA DIAFRAGMA CARBURADOR', 'TAMPA DIAFRAGMA REGULADOR', 'TAMPA DIANT BLOCO', 'TAMPA DISTRIB', 'TAMPA CARBUR', 'TAMPA HOMO MOTOR', 'TAMPA BLOCO MOTOR', 'TAMPA MOTORES', 'TAMPA MOTRIZ PASSAT', 'TAMPA RADIADOR', 'TAMPA REGULAGEM FREIO', 'TAMPA RESERV LIQ FREIO', 'TAMPA RESERV UNIVERSAL', 'TAMPA RESERVATORIO EXPANSAO', 'TAMPA RESERV PARTIDA FRIO', 'TAMPA RESERVATORIO RADIADOR', 'TAMPA VALV', 'TAMPA VALVULA MOTOR', 'TAMPA DINAMO', 'TAMPA VENTIL', 'TAMPAO LATAO', 'TAMPAO BOMBA AGUA', 'TAMPAO CARC VALV', 'TAMPAO MACHO ROSCA',]},
            'tampas_combustivel': {'codigo': '0386', 'itens': ['TAMPA BOMBA COMBUSTIVEL', 'TAMPA RESERV GASOLINA', 'TAMPA TANQUE COMBUSTIVEL', 'TAMPA RESERVATORIO GASOLINA', 'TAMPA TANQUE']},
            'tampas_oleo': {'codigo': '0387', 'itens': ['TAMPA FILTRO OLEO', 'TAMPA OLEO']},
            'tampas_reservatorio_agua': {'codigo': '0388', 'itens': ['TAMPA RESERV AGUA', 'TAMPA RESERVATORIO AGUA', 'TAMPA RESERV LIMPADOR']},
        }
    },
    'transmissao': {
        'codigo': '0036',
        'subgrupos': {
            'default': {'codigo': '0001', 'itens': ['BALENCEIRO EMBREAGEM', 'BARRA DE LIGACAO', 'CAIXA SATELITE', 'CANO EMBREAGEM', 'CAPA ROLAMENTO CARDAN', 'CANO GUIA CABO EMB', 'GUIA ROLAMENTO EMBREAGEM', 'KIT ABRACADEIRA', 'KIT GARFO EMBREAGEM', 'KIT SEPARADOR MOLA', 'PARAFUSO CAMBIO', 'PARAFUSO HOMOCINETICA', 'PARAFUSO CONVERSOR TORQUE', 'PARAFUSO ENGRENAGEM COMANDO', 'PARAFUSO FIXACAO COROA', 'PARAFUSO PIVO GARFO EMBREAGEM', 'PORCA BORBOLETA', 'PORCA HOMOCINETICA', 'RABETA CAIXA']},
            'buchas_transmissao': {'codigo': '0101', 'itens': ['BUCHA CAMBIO', 'BUCHA OLEO', 'BUCHA GARFO EMBR', 'BUCHA ADAPTADOR COMANDO EMBREAG', 'BUCHA LATERAL CAMBIO', 'BUCHA REFIL SUPORTE CAMBIO AUTO', 'GUIA CABO ENGATE MARCHA', 'GUIA PEDAL EMBREAGEM', 'GUIA ROLAMENTO EMBREAGEM', 'EIXO PILOTO 16 DENTES', 'KIT BUCHA CAIXA', 'KIT BUCHA TENSOR']},
            'embreagens': {'codigo': '0082', 'itens': ['DISCO EMBREAGEM', 'EMBREAGEM', 'GARFO EMBREAGEM', 'GARFO SINCRONIZADOR', 'GARFO TULIPA', 'KIT EMBREAGEM', 'PLATO', 'PLATO EMBREAGEM']},
            'engrenagem': {'codigo': '0129', 'itens': ['ENGRENAGEM 2 MARCHA', 'ENGRENAGEM MARCHA', 'ENGRENAGEM 3 MARCHA', 'ENGRENAGEM LIMP PARABR', 'ENGRENAGEM SINCRONIZADOR', 'ENGRENAGEM RE', 'ENGRENAGEM REDUZIDA', 'ENGRENAGEM MARCHA', 'ENGRENAGEM PLANETARIA', 'ENGRENAGEM VELOCIMETRO', 'JOGO ENGRENAGEM DIFERENCIAL', 'KIT ENGRENAGEM COMANDO']},
            'coifas': {'codigo': '0128', 'itens': ['COIFA CAMBIO', 'COIFA GUARDA PO', 'COIFA HASTE SELETORA', 'COIFA HOMOCINETICA', 'COIFA LADO CAMBIO', 'COIFA LADO RODA', 'COIFA RODA', 'COIFA SETOR', 'KIT COIFA CAIXA', 'KIT COIFA CAMBIO']},
            'cilindros_embreagem': {'codigo': '0083', 'itens': ['CILINDRO EMBRAGEM', 'CILINDRO EMB', 'CILINDRO AUXILIAR EMB', 'CILINDRO ESCRAVO']},
            'cilindros_mestre_embreagem': {'codigo': '0117', 'itens': ['CILINDRO MESTRE EMBREAGEM', 'CILINDRO MESTRE EMB']},
            'atuadores_embreagem': {'codigo': '0084', 'itens': ['ATUADOR EMBREAGE']},
            'homocineticas': {'codigo': '0068', 'itens': ['HOMOCINETICA', 'HOMOCINETICA DESLIZANTE', 'HOMOCINETICA RODA', 'JUNTA HOMOCINETICA', 'KIT JUNTA HOMOCINETICA']},
            'kit_coifa_homocinetica': {'codigo': '0092', 'itens': ['KIT COIFA HOMOCINETICA', 'KIT COIFA REPARO HOMOCINETICA']},
            'trizetas': {'codigo': '0094', 'itens': ['TRIZETA']},
            'tulipas': {'codigo': '0152', 'itens': ['TULIPA']},
            'cruzeta': {'codigo': '0125', 'itens': ['CRUZETA']},
            'coxins': {'codigo': '0078', 'itens': ['COXIM CAMBIO', 'COXIM TRANSMISSAO', 'COXIM LADO CAMBIO', 'COXIM RETO CAMBIO', 'COXIM AMORTECEDOR CAMBIO', 'COXIM CARDAN', 'COXIM EXT EIXO']}
        }
    },
}

# Função para criar um card
def create_card(list_id, card_name):
    url = f"https://api.trello.com/1/cards"
    query = {
        'idList': list_id,
        'name': card_name,
        'key': api_key,
        'token': api_token
    }
    response = requests.post(url, params=query)
    if response.status_code == 200:
        return response.json()['id']
    else:
        print(f"Erro ao criar card '{card_name}': {response.text}")
        return None

# Função para criar uma checklist
def create_checklist(card_id, checklist_name):
    url = f"https://api.trello.com/1/checklists"
    query = {
        'idCard': card_id,
        'name': checklist_name,
        'key': api_key,
        'token': api_token
    }
    response = requests.post(url, params=query)
    if response.status_code == 200:
        return response.json()['id']
    else:
        print(f"Erro ao criar checklist '{checklist_name}': {response.text}")
        return None

# Função para adicionar itens na checklist
def add_item_to_checklist(checklist_id, item_name):
    url = f"https://api.trello.com/1/checklists/{checklist_id}/checkItems"
    query = {
        'name': item_name,
        'key': api_key,
        'token': api_token
    }
    response = requests.post(url, params=query)
    if response.status_code == 200:
        print(f"Item '{item_name}' adicionado com sucesso!")
    else:
        print(f"Erro ao adicionar '{item_name}': {response.text}")

# Criar cards, checklists e adicionar itens
for grupo, dados_grupo in dicionario.items():
    card_name = f"{grupo.upper()} - {dados_grupo['codigo']}"
    card_id = create_card(list_id, card_name)
    
    if card_id:
        for subgrupo, dados_subgrupo in dados_grupo['subgrupos'].items():
            checklist_name = f"{subgrupo.upper()} - {dados_subgrupo['codigo']}"
            checklist_id = create_checklist(card_id, checklist_name)
            
            if checklist_id:
                for item in dados_subgrupo['itens']:
                    add_item_to_checklist(checklist_id, item)
